BOT_TOKEN  = "8636653807:AAHZ78mljBGmTNdO4YP3duXwp-RKjkDSusw"
OWNER_ID   = 6671520580
WARN_LIMIT = 3

MONGO_URL = "mongodb://LAKSHMANLOVCHINNU:LAKSH_LUB_CHINNU@ac-kpncihe-shard-00-00.yfyatwy.mongodb.net:27017,ac-kpncihe-shard-00-01.yfyatwy.mongodb.net:27017,ac-kpncihe-shard-00-02.yfyatwy.mongodb.net:27017/?ssl=true&replicaSet=atlas-zftykc-shard-0&authSource=admin"
MONGO_DB_NAME = "telegram_bot"

API_ID   = 30558476
API_HASH = "0842e5d0b9581bc1a5317495692f983c"

JIKAN_API = "https://api.jikan.moe/v4"

RB_COINS_MIN = 3
RB_COINS_MAX = 5

TRIVIA_QUESTIONS = [
    {"q": "What is the capital of France?",                    "a": "paris"},
    {"q": "How many sides does a hexagon have?",               "a": "6"},
    {"q": "What planet is closest to the Sun?",                "a": "mercury"},
    {"q": "Who painted the Mona Lisa?",                        "a": "da vinci"},
    {"q": "What is the largest ocean on Earth?",               "a": "pacific"},
    {"q": "How many continents are there?",                    "a": "7"},
    {"q": "What is the chemical symbol for water?",            "a": "h2o"},
    {"q": "Who wrote Romeo and Juliet?",                       "a": "shakespeare"},
    {"q": "What is the fastest land animal?",                  "a": "cheetah"},
    {"q": "How many bones are in the human body?",             "a": "206"},
    {"q": "Which planet has the most moons?",                  "a": "saturn"},
    {"q": "What is the smallest country in the world?",        "a": "vatican"},
    {"q": "Who invented the telephone?",                       "a": "bell"},
    {"q": "What year did World War II end?",                   "a": "1945"},
    {"q": "What is the tallest mountain in the world?",        "a": "everest"},
    {"q": "How many players are on a football team?",          "a": "11"},
    {"q": "What is the currency of Japan?",                    "a": "yen"},
    {"q": "Who wrote Harry Potter?",                           "a": "rowling"},
    {"q": "What is the speed of light (approx, in km/s)?",    "a": "300000"},
    {"q": "How many strings does a standard guitar have?",     "a": "6"},
    {"q": "What is the capital of India?",                     "a": "new delhi"},
    {"q": "Who is known as the God of Cricket?",               "a": "sachin"},
    {"q": "How many overs in a standard ODI match per side?",  "a": "50"},
    {"q": "Which country invented cricket?",                   "a": "england"},
    {"q": "What does IPL stand for?",                          "a": "indian premier league"},
    {"q": "Who is the fastest bowler in cricket history?",     "a": "shoaib akhtar"},
    {"q": "How many players are on a cricket team?",           "a": "11"},
    {"q": "What is the capital of Japan?",                     "a": "tokyo"},
    {"q": "How many planets are in our solar system?",         "a": "8"},
    {"q": "What is the national sport of India?",              "a": "hockey"},
]

TRUTH_QUESTIONS = [
    "What is your biggest fear?",
    "Have you ever lied to a close friend?",
    "What is the most embarrassing thing you have ever done?",
    "Who do you have a crush on right now?",
    "What is your biggest regret in life?",
    "Have you ever cheated on a test or exam?",
    "What is a secret you have never told anyone in this group?",
    "What is your worst habit?",
    "Have you ever stolen something, even something small?",
    "What is the strangest dream you have ever had?",
    "What would you do with one million dollars?",
    "Have you ever ghosted someone?",
    "What is the most childish thing you still do?",
    "Who in this group do you trust the least?",
    "What is something you pretend to like but actually hate?",
    "What is your most embarrassing music taste?",
    "Have you ever blamed someone else for something you did?",
    "What is the worst lie you have ever told?",
    "What is the most trouble you've ever been in?",
    "Have you ever had a crush on a teacher or boss?",
]

DARE_CHALLENGES = [
    "Send a voice message singing your favourite song right now.",
    "Change your profile picture to something funny for the next hour.",
    "Write a poem about the last person who messaged you.",
    "Type your next 5 messages with your eyes completely closed.",
    "Tell a joke that makes at least one person reply with laughter.",
    "Say something genuinely kind to every person currently in this chat.",
    "Describe yourself in exactly 3 words — no more, no less.",
    "Share the 5th photo from your camera roll.",
    "Write a 2-sentence horror story using: moon, cheese, and robot.",
    "Ask the most random question you can think of to the group.",
    "Speak in rhymes for your next 3 messages.",
    "Send a message in a language you barely know.",
    "Compliment the last person who spoke in this chat.",
    "Send a voice message doing your best celebrity impression.",
    "Post your most recently used emoji 10 times in a row.",
    "Write a fake news headline about someone in this group.",
    "Send a selfie or a photo of what you are doing right now.",
    "Do 10 push-ups and send a voice note counting them out loud.",
    "Type the next message using only emoji, no words.",
    "Call out your own biggest flaw honestly in 1 sentence.",
]

MAGIC_8_BALL_ANSWERS = [
    "It is certain.", "Without a doubt.", "Yes, definitely.",
    "You may rely on it.", "As I see it, yes.", "Most likely.",
    "Outlook good.", "Signs point to yes.", "Reply hazy, try again.",
    "Ask again later.", "Better not tell you now.", "Cannot predict now.",
    "Concentrate and ask again.", "Don't count on it.", "My reply is no.",
    "My sources say no.", "Outlook not so good.", "Very doubtful.",
]

JOKES = [
    "Why don't scientists trust atoms?\n<i>Because they make up everything.</i>",
    "I told my wife she was drawing her eyebrows too high.\n<i>She looked surprised.</i>",
    "Why do cows wear bells?\n<i>Because their horns don't work.</i>",
    "I'm reading a book about anti-gravity.\n<i>It's impossible to put down.</i>",
    "Did you hear about the mathematician afraid of negative numbers?\n<i>He'll stop at nothing to avoid them.</i>",
    "I used to hate facial hair.\n<i>Then it grew on me.</i>",
    "What do you call cheese that isn't yours?\n<i>Nacho cheese.</i>",
    "I would tell you a construction joke, but I'm still working on it.",
    "Why did the scarecrow win an award?\n<i>Because he was outstanding in his field.</i>",
    "What do you call a fake noodle?\n<i>An impasta.</i>",
    "I'm on a seafood diet.\n<i>Every time I see food, I eat it.</i>",
    "Why can't you give Elsa a balloon?\n<i>Because she'll let it go.</i>",
    "What do you call a sleeping dinosaur?\n<i>A dino-snore.</i>",
    "Why did the bicycle fall over?\n<i>Because it was two-tired.</i>",
    "I told my doctor I broke my arm in two places.\n<i>He told me to stop going to those places.</i>",
    "Why did the golfer bring extra pants?\n<i>In case he got a hole in one.</i>",
    "What do you call a bear with no teeth?\n<i>A gummy bear.</i>",
    "I asked my dog what 2 minus 2 is. He said nothing.",
]

HANGMAN_WORDS = [
    "python", "telegram", "hangman", "keyboard", "elephant",
    "mystery", "champion", "adventure", "paradise", "universe",
    "butterfly", "chocolate", "dinosaur", "february", "hospital",
    "invisible", "jealousy", "knowledge", "language", "mountain",
    "notebook", "ordinary", "positive", "question", "rainbow",
    "saturday", "together", "umbrella", "vacation", "weather",
    "cricket", "bollywood", "festival", "monsoon", "rickshaw",
    "philosophy", "democracy", "revolution", "volunteer", "satellite",
]

HANGMAN_STAGES = [
    "```\n  _____\n |     |\n |\n |\n |\n |\n```",
    "```\n  _____\n |     |\n |     O\n |\n |\n |\n```",
    "```\n  _____\n |     |\n |     O\n |     |\n |\n |\n```",
    "```\n  _____\n |     |\n |     O\n |    /|\n |\n |\n```",
    "```\n  _____\n |     |\n |     O\n |    /|\\\n |\n |\n```",
    "```\n  _____\n |     |\n |     O\n |    /|\\\n |    /\n |\n```",
    "```\n  _____\n |     |\n |     O\n |    /|\\\n |    / \\\n |  DEAD\n```",
]

# ── Rarity System ─────────────────────────────────────────────────────────────
RARITY_EMOJI = {
    "Common":    "🔵",
    "Uncommon":  "🟢",
    "Rare":      "🟠",
    "Epic":      "🟣",
    "Legendary": "⭐",
}

RARITY_WEIGHTS = (
    ["Common"]    * 55 +
    ["Uncommon"]  * 25 +
    ["Rare"]      * 12 +
    ["Epic"]      *  6 +
    ["Legendary"] *  2
)

LEGENDARY_CRICKETERS = {
    "Sachin Tendulkar", "Shane Warne", "Don Bradman", "Brian Lara", "Viv Richards",
    "Muttiah Muralitharan", "Jacques Kallis", "Garfield Sobers", "Wasim Akram",
    "Imran Khan", "Glenn McGrath", "Ricky Ponting", "Adam Gilchrist",
    "Anil Kumble", "Kumar Sangakkara", "Mahela Jayawardene", "Allan Donald",
    "Curtly Ambrose", "Malcolm Marshall", "Richard Hadlee", "Kapil Dev",
    "Joel Garner", "Michael Holding", "George Headley", "Wally Hammond",
    "Don Bradman", "Jack Hobbs", "Len Hutton", "Vinoo Mankad", "WG Grace",
    "Keith Miller",
}

EPIC_CRICKETERS = {
    "Virat Kohli", "MS Dhoni", "Rohit Sharma", "Jasprit Bumrah",
    "Steve Smith", "David Warner", "Mitchell Starc", "Pat Cummins",
    "Joe Root", "Ben Stokes", "James Anderson", "Stuart Broad",
    "Babar Azam", "Shaheen Afridi", "Mohammad Rizwan",
    "Rashid Khan", "AB de Villiers", "Dale Steyn", "Kagiso Rabada",
    "Kane Williamson", "Trent Boult", "Tim Southee", "Brendon McCullum",
    "Shakib Al Hasan", "Tamim Iqbal",
    "Lasith Malinga", "Angelo Mathews", "Wanindu Hasaranga",
    "Chris Gayle", "Andre Russell", "Kieron Pollard",
    "Sourav Ganguly", "Rahul Dravid", "Sunil Gavaskar", "VVS Laxman",
    "Ian Botham", "Geoffrey Boycott", "Graham Gooch", "Graeme Smith",
    "Hashim Amla", "AB de Villiers", "Faf du Plessis",
    "Sanath Jayasuriya", "Arjuna Ranatunga", "Aravinda de Silva",
    "Chaminda Vaas", "Lasith Malinga",
    "Clive Lloyd", "Gordon Greenidge", "Desmond Haynes",
    "Martin Crowe", "Stephen Fleming",
    "Mohammad Yousuf", "Inzamam-ul-Haq", "Younis Khan",
    "Saeed Anwar", "Shoaib Akhtar", "Waqar Younis",
    "Andy Flower", "Heath Streak",
}

RARE_CRICKETERS = {
    "Hardik Pandya", "KL Rahul", "Shubman Gill", "Ravindra Jadeja",
    "Ravichandran Ashwin", "Mohammed Shami", "Rishabh Pant",
    "Cheteshwar Pujara", "Ajinkya Rahane", "Shreyas Iyer",
    "Suryakumar Yadav", "Ishan Kishan", "Arshdeep Singh",
    "Nathan Lyon", "Marcus Labuschagne", "Travis Head", "Usman Khawaja",
    "Josh Hazlewood", "Cameron Green",
    "Mark Wood", "Jonny Bairstow", "Jos Buttler", "Zak Crawley",
    "Ben Duckett", "Harry Brook", "Adil Rashid",
    "Shadab Khan", "Mohammad Nawaz", "Naseem Shah", "Iftikhar Ahmed",
    "Fakhar Zaman", "Imam-ul-Haq",
    "Dimuth Karunaratne", "Pathum Nissanka", "Kusal Mendis",
    "Dhananjaya de Silva", "Maheesh Theekshana",
    "Jason Holder", "Nicholas Pooran", "Shai Hope", "Alzarri Joseph",
    "David Miller", "Heinrich Klaasen", "Marco Jansen", "Anrich Nortje",
    "Lungi Ngidi", "Keshav Maharaj", "Temba Bavuma", "Aiden Markram",
    "Tom Latham", "Devon Conway", "Daryl Mitchell",
    "Mushfiqur Rahim", "Mehidy Hasan Miraz", "Liton Das",
    "Mohammad Nabi", "Mujeeb Ur Rahman", "Rahmanullah Gurbaz",
    "Sikandar Raza", "Craig Ervine", "Blessing Muzarabani",
    "Paul Stirling", "Mark Adair", "Harry Tector",
    "Ryan ten Doeschate", "Bas de Leede",
    "Sandeep Lamichhane", "Rohit Kumar Paudel",
}


def get_cricketer_rarity(name: str) -> str:
    """Return rarity level for a cricketer based on predefined sets."""
    if name in LEGENDARY_CRICKETERS:
        return "Legendary"
    if name in EPIC_CRICKETERS:
        return "Epic"
    if name in RARE_CRICKETERS:
        return "Rare"
    # Use name hash for deterministic Uncommon/Common split
    return "Uncommon" if (sum(ord(c) for c in name) % 3 == 0) else "Common"


# ── Anime Characters (with source and rarity) ─────────────────────────────────
FALLBACK_ANIME = [
    {"name": "Naruto Uzumaki",      "image": "https://cdn.myanimelist.net/images/characters/2/284121.jpg",  "anime": "Naruto",                          "rarity": "Legendary"},
    {"name": "Monkey D. Luffy",     "image": "https://cdn.myanimelist.net/images/characters/9/310307.jpg",  "anime": "One Piece",                       "rarity": "Legendary"},
    {"name": "Goku",                "image": "https://cdn.myanimelist.net/images/characters/8/89198.jpg",   "anime": "Dragon Ball Z",                   "rarity": "Legendary"},
    {"name": "Levi Ackerman",       "image": "https://cdn.myanimelist.net/images/characters/2/241413.jpg",  "anime": "Attack on Titan",                 "rarity": "Epic"},
    {"name": "Roronoa Zoro",        "image": "https://cdn.myanimelist.net/images/characters/3/100534.jpg",  "anime": "One Piece",                       "rarity": "Epic"},
    {"name": "Sasuke Uchiha",       "image": "https://cdn.myanimelist.net/images/characters/5/339183.jpg",  "anime": "Naruto",                          "rarity": "Legendary"},
    {"name": "Killua Zoldyck",      "image": "https://cdn.myanimelist.net/images/characters/7/84782.jpg",   "anime": "Hunter x Hunter",                 "rarity": "Epic"},
    {"name": "Itachi Uchiha",       "image": "https://cdn.myanimelist.net/images/characters/15/318245.jpg", "anime": "Naruto",                          "rarity": "Legendary"},
    {"name": "Eren Yeager",         "image": "https://cdn.myanimelist.net/images/characters/10/339781.jpg", "anime": "Attack on Titan",                 "rarity": "Epic"},
    {"name": "Gojo Satoru",         "image": "https://cdn.myanimelist.net/images/characters/8/477243.jpg",  "anime": "Jujutsu Kaisen",                  "rarity": "Legendary"},
    {"name": "Edward Elric",        "image": "https://cdn.myanimelist.net/images/characters/8/81958.jpg",   "anime": "Fullmetal Alchemist: Brotherhood", "rarity": "Epic"},
    {"name": "Spike Spiegel",       "image": "https://cdn.myanimelist.net/images/characters/4/50197.jpg",   "anime": "Cowboy Bebop",                    "rarity": "Rare"},
    {"name": "Light Yagami",        "image": "https://cdn.myanimelist.net/images/characters/2/253847.jpg",  "anime": "Death Note",                      "rarity": "Epic"},
    {"name": "L Lawliet",           "image": "https://cdn.myanimelist.net/images/characters/2/74737.jpg",   "anime": "Death Note",                      "rarity": "Epic"},
    {"name": "Ryuk",                "image": "https://cdn.myanimelist.net/images/characters/8/253864.jpg",  "anime": "Death Note",                      "rarity": "Rare"},
    {"name": "Mikasa Ackerman",     "image": "https://cdn.myanimelist.net/images/characters/9/215563.jpg",  "anime": "Attack on Titan",                 "rarity": "Epic"},
    {"name": "Vegeta",              "image": "https://cdn.myanimelist.net/images/characters/3/72579.jpg",   "anime": "Dragon Ball Z",                   "rarity": "Epic"},
    {"name": "Kakashi Hatake",      "image": "https://cdn.myanimelist.net/images/characters/7/284129.jpg",  "anime": "Naruto",                          "rarity": "Epic"},
    {"name": "Anya Forger",         "image": "https://cdn.myanimelist.net/images/characters/9/461234.jpg",  "anime": "Spy x Family",                    "rarity": "Legendary"},
    {"name": "Nezuko Kamado",       "image": "https://cdn.myanimelist.net/images/characters/3/431017.jpg",  "anime": "Demon Slayer",                    "rarity": "Epic"},
    {"name": "Tanjiro Kamado",      "image": "https://cdn.myanimelist.net/images/characters/7/431015.jpg",  "anime": "Demon Slayer",                    "rarity": "Epic"},
    {"name": "Zenitsu Agatsuma",    "image": "https://cdn.myanimelist.net/images/characters/8/431019.jpg",  "anime": "Demon Slayer",                    "rarity": "Rare"},
    {"name": "Inosuke Hashibira",   "image": "https://cdn.myanimelist.net/images/characters/3/431014.jpg",  "anime": "Demon Slayer",                    "rarity": "Rare"},
    {"name": "Yuji Itadori",        "image": "https://cdn.myanimelist.net/images/characters/8/477248.jpg",  "anime": "Jujutsu Kaisen",                  "rarity": "Epic"},
    {"name": "Megumi Fushiguro",    "image": "https://cdn.myanimelist.net/images/characters/5/477246.jpg",  "anime": "Jujutsu Kaisen",                  "rarity": "Rare"},
    {"name": "Nobara Kugisaki",     "image": "https://cdn.myanimelist.net/images/characters/4/477245.jpg",  "anime": "Jujutsu Kaisen",                  "rarity": "Rare"},
    {"name": "Ryomen Sukuna",       "image": "https://cdn.myanimelist.net/images/characters/1/477244.jpg",  "anime": "Jujutsu Kaisen",                  "rarity": "Legendary"},
    {"name": "Denji",               "image": "https://cdn.myanimelist.net/images/characters/7/490586.jpg",  "anime": "Chainsaw Man",                    "rarity": "Epic"},
    {"name": "Power",               "image": "https://cdn.myanimelist.net/images/characters/7/490590.jpg",  "anime": "Chainsaw Man",                    "rarity": "Rare"},
    {"name": "Makima",              "image": "https://cdn.myanimelist.net/images/characters/4/490589.jpg",  "anime": "Chainsaw Man",                    "rarity": "Epic"},
    {"name": "Hinata Hyuga",        "image": "https://cdn.myanimelist.net/images/characters/1/290284.jpg",  "anime": "Naruto",                          "rarity": "Rare"},
    {"name": "Nami",                "image": "https://cdn.myanimelist.net/images/characters/7/265186.jpg",  "anime": "One Piece",                       "rarity": "Rare"},
    {"name": "Sanji",               "image": "https://cdn.myanimelist.net/images/characters/2/264960.jpg",  "anime": "One Piece",                       "rarity": "Rare"},
    {"name": "Portgas D. Ace",      "image": "https://cdn.myanimelist.net/images/characters/8/299537.jpg",  "anime": "One Piece",                       "rarity": "Epic"},
    {"name": "Trafalgar Law",       "image": "https://cdn.myanimelist.net/images/characters/2/288148.jpg",  "anime": "One Piece",                       "rarity": "Rare"},
    {"name": "Shanks",              "image": "https://cdn.myanimelist.net/images/characters/7/265127.jpg",  "anime": "One Piece",                       "rarity": "Legendary"},
    {"name": "Gorou",               "image": "https://cdn.myanimelist.net/images/characters/5/514494.jpg",  "anime": "Oshi no Ko",                      "rarity": "Uncommon"},
    {"name": "Ai Hoshino",          "image": "https://cdn.myanimelist.net/images/characters/4/514495.jpg",  "anime": "Oshi no Ko",                      "rarity": "Legendary"},
    {"name": "Aqua Hoshino",        "image": "https://cdn.myanimelist.net/images/characters/6/514497.jpg",  "anime": "Oshi no Ko",                      "rarity": "Rare"},
    {"name": "Armin Arlert",        "image": "https://cdn.myanimelist.net/images/characters/3/339779.jpg",  "anime": "Attack on Titan",                 "rarity": "Rare"},
    {"name": "Historia Reiss",      "image": "https://cdn.myanimelist.net/images/characters/6/339783.jpg",  "anime": "Attack on Titan",                 "rarity": "Uncommon"},
    {"name": "Rem",                 "image": "https://cdn.myanimelist.net/images/characters/4/400490.jpg",  "anime": "Re:Zero",                         "rarity": "Epic"},
    {"name": "Ram",                 "image": "https://cdn.myanimelist.net/images/characters/3/400489.jpg",  "anime": "Re:Zero",                         "rarity": "Rare"},
    {"name": "Emilia",              "image": "https://cdn.myanimelist.net/images/characters/9/400487.jpg",  "anime": "Re:Zero",                         "rarity": "Rare"},
    {"name": "Subaru Natsuki",      "image": "https://cdn.myanimelist.net/images/characters/2/400488.jpg",  "anime": "Re:Zero",                         "rarity": "Uncommon"},
    {"name": "Shouto Todoroki",     "image": "https://cdn.myanimelist.net/images/characters/2/399012.jpg",  "anime": "My Hero Academia",                "rarity": "Epic"},
    {"name": "Izuku Midoriya",      "image": "https://cdn.myanimelist.net/images/characters/9/399011.jpg",  "anime": "My Hero Academia",                "rarity": "Epic"},
    {"name": "Katsuki Bakugou",     "image": "https://cdn.myanimelist.net/images/characters/5/399014.jpg",  "anime": "My Hero Academia",                "rarity": "Rare"},
    {"name": "All Might",           "image": "https://cdn.myanimelist.net/images/characters/4/399013.jpg",  "anime": "My Hero Academia",                "rarity": "Legendary"},
    {"name": "Erza Scarlet",        "image": "https://cdn.myanimelist.net/images/characters/4/78335.jpg",   "anime": "Fairy Tail",                      "rarity": "Epic"},
    {"name": "Natsu Dragneel",      "image": "https://cdn.myanimelist.net/images/characters/8/320691.jpg",  "anime": "Fairy Tail",                      "rarity": "Rare"},
    {"name": "Lucy Heartfilia",     "image": "https://cdn.myanimelist.net/images/characters/7/78330.jpg",   "anime": "Fairy Tail",                      "rarity": "Uncommon"},
    {"name": "Gon Freecss",         "image": "https://cdn.myanimelist.net/images/characters/3/49101.jpg",   "anime": "Hunter x Hunter",                 "rarity": "Epic"},
    {"name": "Kurapika",            "image": "https://cdn.myanimelist.net/images/characters/9/49098.jpg",   "anime": "Hunter x Hunter",                 "rarity": "Rare"},
    {"name": "Hisoka",              "image": "https://cdn.myanimelist.net/images/characters/9/49096.jpg",   "anime": "Hunter x Hunter",                 "rarity": "Epic"},
    {"name": "Alphonse Elric",      "image": "https://cdn.myanimelist.net/images/characters/9/81959.jpg",   "anime": "Fullmetal Alchemist: Brotherhood", "rarity": "Rare"},
    {"name": "Roy Mustang",         "image": "https://cdn.myanimelist.net/images/characters/2/71285.jpg",   "anime": "Fullmetal Alchemist: Brotherhood", "rarity": "Rare"},
    {"name": "Winry Rockbell",      "image": "https://cdn.myanimelist.net/images/characters/4/39009.jpg",   "anime": "Fullmetal Alchemist: Brotherhood", "rarity": "Uncommon"},
    {"name": "Alucard",             "image": "https://cdn.myanimelist.net/images/characters/5/53294.jpg",   "anime": "Hellsing Ultimate",               "rarity": "Legendary"},
    {"name": "Zero Two",            "image": "https://cdn.myanimelist.net/images/characters/3/430640.jpg",  "anime": "Darling in the FranXX",           "rarity": "Legendary"},
    {"name": "Violet Evergarden",   "image": "https://cdn.myanimelist.net/images/characters/7/430642.jpg",  "anime": "Violet Evergarden",               "rarity": "Epic"},
    {"name": "Kirito",              "image": "https://cdn.myanimelist.net/images/characters/7/204821.jpg",  "anime": "Sword Art Online",                "rarity": "Rare"},
    {"name": "Asuna Yuuki",         "image": "https://cdn.myanimelist.net/images/characters/5/204823.jpg",  "anime": "Sword Art Online",                "rarity": "Rare"},
    {"name": "Ryuko Matoi",         "image": "https://cdn.myanimelist.net/images/characters/3/350297.jpg",  "anime": "Kill la Kill",                    "rarity": "Rare"},
    {"name": "Saber",               "image": "https://cdn.myanimelist.net/images/characters/2/57341.jpg",   "anime": "Fate/stay night",                 "rarity": "Epic"},
    {"name": "Gilgamesh",           "image": "https://cdn.myanimelist.net/images/characters/2/59682.jpg",   "anime": "Fate/Zero",                       "rarity": "Legendary"},
    {"name": "Tohka Yatogami",      "image": "https://cdn.myanimelist.net/images/characters/3/350291.jpg",  "anime": "Date A Live",                     "rarity": "Rare"},
    {"name": "Osamu Dazai",         "image": "https://cdn.myanimelist.net/images/characters/3/421137.jpg",  "anime": "Bungo Stray Dogs",                "rarity": "Epic"},
    {"name": "Ryunosuke Akutagawa", "image": "https://cdn.myanimelist.net/images/characters/5/421141.jpg",  "anime": "Bungo Stray Dogs",                "rarity": "Rare"},
    {"name": "Rimuru Tempest",      "image": "https://cdn.myanimelist.net/images/characters/5/430760.jpg",  "anime": "That Time I Got Reincarnated as a Slime", "rarity": "Legendary"},
    {"name": "Ainz Ooal Gown",      "image": "https://cdn.myanimelist.net/images/characters/4/367227.jpg",  "anime": "Overlord",                        "rarity": "Legendary"},
    {"name": "Albedo",              "image": "https://cdn.myanimelist.net/images/characters/3/367226.jpg",  "anime": "Overlord",                        "rarity": "Rare"},
    {"name": "Kazuma Satou",        "image": "https://cdn.myanimelist.net/images/characters/7/388736.jpg",  "anime": "KonoSuba",                        "rarity": "Uncommon"},
    {"name": "Aqua",                "image": "https://cdn.myanimelist.net/images/characters/5/388738.jpg",  "anime": "KonoSuba",                        "rarity": "Rare"},
    {"name": "Megumin",             "image": "https://cdn.myanimelist.net/images/characters/3/388741.jpg",  "anime": "KonoSuba",                        "rarity": "Epic"},
    {"name": "Darkness",            "image": "https://cdn.myanimelist.net/images/characters/9/388740.jpg",  "anime": "KonoSuba",                        "rarity": "Uncommon"},
    {"name": "Shinobu Kocho",       "image": "https://cdn.myanimelist.net/images/characters/6/431022.jpg",  "anime": "Demon Slayer",                    "rarity": "Epic"},
    {"name": "Tengen Uzui",         "image": "https://cdn.myanimelist.net/images/characters/4/431021.jpg",  "anime": "Demon Slayer",                    "rarity": "Rare"},
    {"name": "Rengoku Kyojuro",     "image": "https://cdn.myanimelist.net/images/characters/3/431020.jpg",  "anime": "Demon Slayer",                    "rarity": "Epic"},
    {"name": "Giyu Tomioka",        "image": "https://cdn.myanimelist.net/images/characters/8/431016.jpg",  "anime": "Demon Slayer",                    "rarity": "Rare"},
    {"name": "Muzan Kibutsuji",     "image": "https://cdn.myanimelist.net/images/characters/5/431023.jpg",  "anime": "Demon Slayer",                    "rarity": "Legendary"},
    {"name": "Tohru",               "image": "https://cdn.myanimelist.net/images/characters/5/430651.jpg",  "anime": "Miss Kobayashi's Dragon Maid",    "rarity": "Rare"},
    {"name": "Takina Inoue",        "image": "https://cdn.myanimelist.net/images/characters/3/513882.jpg",  "anime": "Lycoris Recoil",                  "rarity": "Rare"},
    {"name": "Chisato Nishikigi",   "image": "https://cdn.myanimelist.net/images/characters/7/513883.jpg",  "anime": "Lycoris Recoil",                  "rarity": "Epic"},
    {"name": "Yor Forger",          "image": "https://cdn.myanimelist.net/images/characters/5/461233.jpg",  "anime": "Spy x Family",                    "rarity": "Epic"},
    {"name": "Loid Forger",         "image": "https://cdn.myanimelist.net/images/characters/7/461236.jpg",  "anime": "Spy x Family",                    "rarity": "Rare"},
    {"name": "Rias Gremory",        "image": "https://cdn.myanimelist.net/images/characters/3/350295.jpg",  "anime": "High School DxD",                 "rarity": "Epic"},
    {"name": "Akeno Himejima",      "image": "https://cdn.myanimelist.net/images/characters/4/350298.jpg",  "anime": "High School DxD",                 "rarity": "Rare"},
    {"name": "Issei Hyoudou",       "image": "https://cdn.myanimelist.net/images/characters/2/350293.jpg",  "anime": "High School DxD",                 "rarity": "Uncommon"},
    {"name": "Usagi Tsukino",       "image": "https://cdn.myanimelist.net/images/characters/5/53470.jpg",   "anime": "Sailor Moon",                     "rarity": "Legendary"},
    {"name": "Ranma Saotome",       "image": "https://cdn.myanimelist.net/images/characters/3/28907.jpg",   "anime": "Ranma 1/2",                       "rarity": "Rare"},
    {"name": "Inuyasha",            "image": "https://cdn.myanimelist.net/images/characters/2/54655.jpg",   "anime": "Inuyasha",                        "rarity": "Rare"},
    {"name": "Sesshomaru",          "image": "https://cdn.myanimelist.net/images/characters/2/54656.jpg",   "anime": "Inuyasha",                        "rarity": "Epic"},
    {"name": "Gintoki Sakata",      "image": "https://cdn.myanimelist.net/images/characters/4/49070.jpg",   "anime": "Gintama",                         "rarity": "Epic"},
    {"name": "Kagura",              "image": "https://cdn.myanimelist.net/images/characters/4/49071.jpg",   "anime": "Gintama",                         "rarity": "Rare"},
    {"name": "Kenshin Himura",      "image": "https://cdn.myanimelist.net/images/characters/3/72508.jpg",   "anime": "Rurouni Kenshin",                 "rarity": "Epic"},
    {"name": "Ichigo Kurosaki",     "image": "https://cdn.myanimelist.net/images/characters/2/120371.jpg",  "anime": "Bleach",                          "rarity": "Epic"},
    {"name": "Rukia Kuchiki",       "image": "https://cdn.myanimelist.net/images/characters/6/71233.jpg",   "anime": "Bleach",                          "rarity": "Rare"},
    {"name": "Byakuya Kuchiki",     "image": "https://cdn.myanimelist.net/images/characters/9/71235.jpg",   "anime": "Bleach",                          "rarity": "Rare"},
    {"name": "Kisuke Urahara",      "image": "https://cdn.myanimelist.net/images/characters/9/71237.jpg",   "anime": "Bleach",                          "rarity": "Epic"},
    {"name": "Sosuke Aizen",        "image": "https://cdn.myanimelist.net/images/characters/2/71236.jpg",   "anime": "Bleach",                          "rarity": "Legendary"},
    {"name": "Jonathan Joestar",    "image": "https://cdn.myanimelist.net/images/characters/2/104702.jpg",  "anime": "JoJo's Bizarre Adventure",        "rarity": "Rare"},
    {"name": "Jotaro Kujo",         "image": "https://cdn.myanimelist.net/images/characters/2/350307.jpg",  "anime": "JoJo's Bizarre Adventure",        "rarity": "Epic"},
    {"name": "Giorno Giovanna",     "image": "https://cdn.myanimelist.net/images/characters/4/350309.jpg",  "anime": "JoJo's Bizarre Adventure",        "rarity": "Legendary"},
    {"name": "Dio Brando",          "image": "https://cdn.myanimelist.net/images/characters/7/104705.jpg",  "anime": "JoJo's Bizarre Adventure",        "rarity": "Legendary"},
    {"name": "Kira Yoshikage",      "image": "https://cdn.myanimelist.net/images/characters/6/350311.jpg",  "anime": "JoJo's Bizarre Adventure",        "rarity": "Epic"},
    {"name": "Speed Wagon",         "image": "https://cdn.myanimelist.net/images/characters/9/104707.jpg",  "anime": "JoJo's Bizarre Adventure",        "rarity": "Common"},
    {"name": "Rohan Kishibe",       "image": "https://cdn.myanimelist.net/images/characters/5/350313.jpg",  "anime": "JoJo's Bizarre Adventure",        "rarity": "Rare"},
]

# Total anime series represented in FALLBACK_ANIME (for harem totals)
ANIME_SERIES_TOTALS = {
    "Naruto":                           50,
    "One Piece":                        100,
    "Dragon Ball Z":                    40,
    "Attack on Titan":                  30,
    "Hunter x Hunter":                  25,
    "Jujutsu Kaisen":                   25,
    "Demon Slayer":                     30,
    "Chainsaw Man":                     20,
    "Re:Zero":                          20,
    "My Hero Academia":                 40,
    "Fairy Tail":                       35,
    "Fullmetal Alchemist: Brotherhood": 25,
    "Death Note":                       20,
    "Spy x Family":                     15,
    "Bleach":                           40,
    "JoJo's Bizarre Adventure":         50,
    "Sword Art Online":                 20,
    "Cowboy Bebop":                     10,
    "KonoSuba":                         15,
    "Overlord":                         20,
    "Gintama":                          30,
}


# ── Cricketers (850+ international cricketers) ────────────────────────────────
CRICKETERS = [
    # ── India ────────────────────────────────────────────────────────────────
    {"name": "Virat Kohli",              "wiki_title": "Virat_Kohli"},
    {"name": "MS Dhoni",                 "wiki_title": "MS_Dhoni"},
    {"name": "Rohit Sharma",             "wiki_title": "Rohit_Sharma"},
    {"name": "Sachin Tendulkar",         "wiki_title": "Sachin_Tendulkar"},
    {"name": "Sourav Ganguly",           "wiki_title": "Sourav_Ganguly"},
    {"name": "Rahul Dravid",             "wiki_title": "Rahul_Dravid"},
    {"name": "VVS Laxman",               "wiki_title": "VVS_Laxman"},
    {"name": "Anil Kumble",              "wiki_title": "Anil_Kumble"},
    {"name": "Kapil Dev",                "wiki_title": "Kapil_Dev"},
    {"name": "Sunil Gavaskar",           "wiki_title": "Sunil_Gavaskar"},
    {"name": "Hardik Pandya",            "wiki_title": "Hardik_Pandya"},
    {"name": "KL Rahul",                 "wiki_title": "KL_Rahul"},
    {"name": "Shubman Gill",             "wiki_title": "Shubman_Gill"},
    {"name": "Jasprit Bumrah",           "wiki_title": "Jasprit_Bumrah"},
    {"name": "Ravindra Jadeja",          "wiki_title": "Ravindra_Jadeja"},
    {"name": "Ravichandran Ashwin",      "wiki_title": "Ravichandran_Ashwin"},
    {"name": "Mohammed Shami",           "wiki_title": "Mohammed_Shami"},
    {"name": "Rishabh Pant",             "wiki_title": "Rishabh_Pant"},
    {"name": "Cheteshwar Pujara",        "wiki_title": "Cheteshwar_Pujara"},
    {"name": "Ajinkya Rahane",           "wiki_title": "Ajinkya_Rahane"},
    {"name": "Virender Sehwag",          "wiki_title": "Virender_Sehwag"},
    {"name": "Gautam Gambhir",           "wiki_title": "Gautam_Gambhir"},
    {"name": "Yuvraj Singh",             "wiki_title": "Yuvraj_Singh"},
    {"name": "Harbhajan Singh",          "wiki_title": "Harbhajan_Singh"},
    {"name": "Zaheer Khan",              "wiki_title": "Zaheer_Khan"},
    {"name": "Irfan Pathan",             "wiki_title": "Irfan_Pathan"},
    {"name": "Yusuf Pathan",             "wiki_title": "Yusuf_Pathan"},
    {"name": "Suresh Raina",             "wiki_title": "Suresh_Raina"},
    {"name": "Dinesh Karthik",           "wiki_title": "Dinesh_Karthik"},
    {"name": "Murali Vijay",             "wiki_title": "Murali_Vijay"},
    {"name": "Ambati Rayudu",            "wiki_title": "Ambati_Rayudu"},
    {"name": "Kedar Jadhav",             "wiki_title": "Kedar_Jadhav"},
    {"name": "Manish Pandey",            "wiki_title": "Manish_Pandey"},
    {"name": "Mohammed Siraj",           "wiki_title": "Mohammed_Siraj"},
    {"name": "Shreyas Iyer",             "wiki_title": "Shreyas_Iyer"},
    {"name": "Ishan Kishan",             "wiki_title": "Ishan_Kishan"},
    {"name": "Suryakumar Yadav",         "wiki_title": "Suryakumar_Yadav"},
    {"name": "Arshdeep Singh",           "wiki_title": "Arshdeep_Singh"},
    {"name": "Deepak Chahar",            "wiki_title": "Deepak_Chahar"},
    {"name": "Bhuvneshwar Kumar",        "wiki_title": "Bhuvneshwar_Kumar"},
    {"name": "Umesh Yadav",              "wiki_title": "Umesh_Yadav"},
    {"name": "Ishant Sharma",            "wiki_title": "Ishant_Sharma"},
    {"name": "Washington Sundar",        "wiki_title": "Washington_Sundar"},
    {"name": "Axar Patel",               "wiki_title": "Axar_Patel"},
    {"name": "Shardul Thakur",           "wiki_title": "Shardul_Thakur"},
    {"name": "Kuldeep Yadav",            "wiki_title": "Kuldeep_Yadav"},
    {"name": "Prithvi Shaw",             "wiki_title": "Prithvi_Shaw"},
    {"name": "Yashasvi Jaiswal",         "wiki_title": "Yashasvi_Jaiswal"},
    {"name": "Ruturaj Gaikwad",          "wiki_title": "Ruturaj_Gaikwad"},
    {"name": "Tilak Varma",              "wiki_title": "Tilak_Varma"},
    {"name": "Shivam Dube",              "wiki_title": "Shivam_Dube"},
    {"name": "Prasidh Krishna",          "wiki_title": "Prasidh_Krishna"},
    {"name": "Avesh Khan",               "wiki_title": "Avesh_Khan"},
    {"name": "Khaleel Ahmed",            "wiki_title": "Khaleel_Ahmed"},
    {"name": "Jaydev Unadkat",           "wiki_title": "Jaydev_Unadkat"},
    {"name": "Navdeep Saini",            "wiki_title": "Navdeep_Saini"},
    {"name": "Venkatesh Iyer",           "wiki_title": "Venkatesh_Iyer"},
    {"name": "Sanju Samson",             "wiki_title": "Sanju_Samson"},
    {"name": "Devdutt Padikkal",         "wiki_title": "Devdutt_Padikkal"},
    {"name": "Nitish Kumar Reddy",       "wiki_title": "Nitish_Kumar_Reddy"},
    {"name": "Harshit Rana",             "wiki_title": "Harshit_Rana"},
    {"name": "Wriddhiman Saha",          "wiki_title": "Wriddhiman_Saha"},
    {"name": "Abhinav Mukund",           "wiki_title": "Abhinav_Mukund"},
    {"name": "Piyush Chawla",            "wiki_title": "Piyush_Chawla"},
    {"name": "S Sreesanth",              "wiki_title": "S._Sreesanth"},
    {"name": "Munaf Patel",              "wiki_title": "Munaf_Patel"},
    {"name": "RP Singh",                 "wiki_title": "RP_Singh"},
    {"name": "Saurav Ganguly",           "wiki_title": "Sourav_Ganguly"},
    {"name": "Ajay Ratra",               "wiki_title": "Ajay_Ratra"},
    {"name": "Deep Dasgupta",            "wiki_title": "Deep_Dasgupta"},
    {"name": "MSK Prasad",               "wiki_title": "MSK_Prasad"},
    {"name": "Syed Kirmani",             "wiki_title": "Syed_Kirmani"},
    {"name": "Roger Binny",              "wiki_title": "Roger_Binny"},
    {"name": "Madan Lal",                "wiki_title": "Madan_Lal_(cricketer)"},
    {"name": "Kiran More",               "wiki_title": "Kiran_More"},
    {"name": "Sanjay Manjrekar",         "wiki_title": "Sanjay_Manjrekar"},
    {"name": "Praveen Amre",             "wiki_title": "Praveen_Amre"},
    {"name": "Vinod Kambli",             "wiki_title": "Vinod_Kambli"},
    {"name": "Robin Singh",              "wiki_title": "Robin_Singh_(cricketer)"},
    {"name": "Vinoo Mankad",             "wiki_title": "Vinoo_Mankad"},
    {"name": "CK Nayudu",                "wiki_title": "C._K._Nayudu"},
    {"name": "Vijay Hazare",             "wiki_title": "Vijay_Hazare"},
    {"name": "Chetan Sharma",            "wiki_title": "Chetan_Sharma_(cricketer)"},
    {"name": "Manoj Prabhakar",          "wiki_title": "Manoj_Prabhakar"},
    {"name": "Krishnamurthy Srikkanth",  "wiki_title": "Kris_Srikkanth"},
    {"name": "Narendra Hirwani",         "wiki_title": "Narendra_Hirwani"},
    {"name": "Laxman Sivaramakrishnan",  "wiki_title": "Laxman_Sivaramakrishnan"},
    {"name": "Maninder Singh",           "wiki_title": "Maninder_Singh_(cricketer)"},
    {"name": "Dilip Sardesai",           "wiki_title": "Dilip_Sardesai"},
    {"name": "Ajit Wadekar",             "wiki_title": "Ajit_Wadekar"},
    {"name": "Eknath Solkar",            "wiki_title": "Eknath_Solkar"},
    {"name": "Chandu Borde",             "wiki_title": "Chandu_Borde"},
    {"name": "Subhash Gupte",            "wiki_title": "Subhash_Gupte"},
    {"name": "Vijay Manjrekar",          "wiki_title": "Vijay_Manjrekar"},
    {"name": "Hanumant Singh",           "wiki_title": "Hanumant_Singh"},
    {"name": "Nari Contractor",          "wiki_title": "Nari_Contractor"},
    {"name": "Pankaj Roy",               "wiki_title": "Pankaj_Roy_(cricketer)"},
    {"name": "Dattu Phadkar",            "wiki_title": "Dattu_Phadkar"},
    # ── Australia ─────────────────────────────────────────────────────────────
    {"name": "Steve Smith",              "wiki_title": "Steve_Smith_(cricketer)"},
    {"name": "David Warner",             "wiki_title": "David_Warner_(cricketer)"},
    {"name": "Pat Cummins",              "wiki_title": "Pat_Cummins"},
    {"name": "Mitchell Starc",           "wiki_title": "Mitchell_Starc"},
    {"name": "Josh Hazlewood",           "wiki_title": "Josh_Hazlewood"},
    {"name": "Nathan Lyon",              "wiki_title": "Nathan_Lyon_(cricketer)"},
    {"name": "Travis Head",              "wiki_title": "Travis_Head_(cricketer)"},
    {"name": "Usman Khawaja",            "wiki_title": "Usman_Khawaja"},
    {"name": "Marnus Labuschagne",       "wiki_title": "Marnus_Labuschagne"},
    {"name": "Cameron Green",            "wiki_title": "Cameron_Green_(cricketer)"},
    {"name": "Aaron Finch",              "wiki_title": "Aaron_Finch_(cricketer)"},
    {"name": "Matthew Wade",             "wiki_title": "Matthew_Wade_(cricketer)"},
    {"name": "Marcus Stoinis",           "wiki_title": "Marcus_Stoinis"},
    {"name": "Glenn Maxwell",            "wiki_title": "Glenn_Maxwell"},
    {"name": "Ricky Ponting",            "wiki_title": "Ricky_Ponting"},
    {"name": "Adam Gilchrist",           "wiki_title": "Adam_Gilchrist"},
    {"name": "Shane Warne",              "wiki_title": "Shane_Warne"},
    {"name": "Glenn McGrath",            "wiki_title": "Glenn_McGrath"},
    {"name": "Matthew Hayden",           "wiki_title": "Matthew_Hayden"},
    {"name": "Justin Langer",            "wiki_title": "Justin_Langer"},
    {"name": "Damien Martyn",            "wiki_title": "Damien_Martyn"},
    {"name": "Michael Clarke",           "wiki_title": "Michael_Clarke_(cricketer)"},
    {"name": "Michael Hussey",           "wiki_title": "Mike_Hussey"},
    {"name": "Simon Katich",             "wiki_title": "Simon_Katich"},
    {"name": "Brad Haddin",              "wiki_title": "Brad_Haddin"},
    {"name": "Tim Paine",                "wiki_title": "Tim_Paine"},
    {"name": "Chris Rogers",             "wiki_title": "Chris_Rogers_(cricketer)"},
    {"name": "Cameron Bancroft",         "wiki_title": "Cameron_Bancroft"},
    {"name": "Matthew Renshaw",          "wiki_title": "Matthew_Renshaw_(cricketer)"},
    {"name": "Phil Hughes",              "wiki_title": "Phil_Hughes_(cricketer)"},
    {"name": "Ian Chappell",             "wiki_title": "Ian_Chappell"},
    {"name": "Greg Chappell",            "wiki_title": "Greg_Chappell"},
    {"name": "Kim Hughes",               "wiki_title": "Kim_Hughes_(cricketer)"},
    {"name": "Dean Jones",               "wiki_title": "Dean_Jones_(cricketer)"},
    {"name": "David Hookes",             "wiki_title": "David_Hookes"},
    {"name": "Mark Taylor",              "wiki_title": "Mark_Taylor_(cricketer)"},
    {"name": "Michael Bevan",            "wiki_title": "Michael_Bevan"},
    {"name": "Jason Gillespie",          "wiki_title": "Jason_Gillespie"},
    {"name": "Brett Lee",                "wiki_title": "Brett_Lee"},
    {"name": "Merv Hughes",              "wiki_title": "Merv_Hughes"},
    {"name": "Craig McDermott",          "wiki_title": "Craig_McDermott"},
    {"name": "Stuart MacGill",           "wiki_title": "Stuart_MacGill"},
    {"name": "Andrew Symonds",           "wiki_title": "Andrew_Symonds"},
    {"name": "Darren Lehmann",           "wiki_title": "Darren_Lehmann"},
    {"name": "Mark Waugh",               "wiki_title": "Mark_Waugh"},
    {"name": "Steve Waugh",              "wiki_title": "Steve_Waugh"},
    {"name": "Don Bradman",              "wiki_title": "Don_Bradman"},
    {"name": "Keith Miller",             "wiki_title": "Keith_Miller"},
    {"name": "Ray Lindwall",             "wiki_title": "Ray_Lindwall"},
    {"name": "Arthur Morris",            "wiki_title": "Arthur_Morris"},
    {"name": "Neil Harvey",              "wiki_title": "Neil_Harvey"},
    {"name": "Alan Davidson",            "wiki_title": "Alan_Davidson_(cricketer)"},
    {"name": "Richie Benaud",            "wiki_title": "Richie_Benaud"},
    {"name": "Graham McKenzie",          "wiki_title": "Graham_McKenzie"},
    {"name": "Doug Walters",             "wiki_title": "Doug_Walters"},
    {"name": "Rodney Marsh",             "wiki_title": "Rodney_Marsh"},
    {"name": "David Hussey",             "wiki_title": "David_Hussey"},
    {"name": "Scott Boland",             "wiki_title": "Scott_Boland"},
    {"name": "Josh Inglis",              "wiki_title": "Josh_Inglis_(cricketer)"},
    {"name": "Tim David",                "wiki_title": "Tim_David"},
    {"name": "Sean Abbott",              "wiki_title": "Sean_Abbott"},
    {"name": "Peter Siddle",             "wiki_title": "Peter_Siddle"},
    {"name": "Ryan Harris",              "wiki_title": "Ryan_Harris_(cricketer)"},
    # ── England ───────────────────────────────────────────────────────────────
    {"name": "Joe Root",                 "wiki_title": "Joe_Root"},
    {"name": "Ben Stokes",               "wiki_title": "Ben_Stokes"},
    {"name": "James Anderson",           "wiki_title": "James_Anderson_(cricketer)"},
    {"name": "Stuart Broad",             "wiki_title": "Stuart_Broad"},
    {"name": "Jonny Bairstow",           "wiki_title": "Jonny_Bairstow"},
    {"name": "Jos Buttler",              "wiki_title": "Jos_Buttler"},
    {"name": "Zak Crawley",              "wiki_title": "Zak_Crawley"},
    {"name": "Ben Duckett",              "wiki_title": "Ben_Duckett"},
    {"name": "Harry Brook",              "wiki_title": "Harry_Brook"},
    {"name": "Ollie Pope",               "wiki_title": "Ollie_Pope_(cricketer)"},
    {"name": "Mark Wood",                "wiki_title": "Mark_Wood_(cricketer)"},
    {"name": "Adil Rashid",              "wiki_title": "Adil_Rashid"},
    {"name": "Chris Jordan",             "wiki_title": "Chris_Jordan_(cricketer)"},
    {"name": "Rehan Ahmed",              "wiki_title": "Rehan_Ahmed_(cricketer)"},
    {"name": "Jamie Overton",            "wiki_title": "Jamie_Overton"},
    {"name": "Moeen Ali",                "wiki_title": "Moeen_Ali"},
    {"name": "Kevin Pietersen",          "wiki_title": "Kevin_Pietersen"},
    {"name": "Paul Collingwood",         "wiki_title": "Paul_Collingwood"},
    {"name": "Marcus Trescothick",       "wiki_title": "Marcus_Trescothick"},
    {"name": "Graeme Swann",             "wiki_title": "Graeme_Swann"},
    {"name": "Tim Bresnan",              "wiki_title": "Tim_Bresnan"},
    {"name": "Monty Panesar",            "wiki_title": "Monty_Panesar"},
    {"name": "Ian Bell",                 "wiki_title": "Ian_Bell"},
    {"name": "Jonathan Trott",           "wiki_title": "Jonathan_Trott"},
    {"name": "Alastair Cook",            "wiki_title": "Alastair_Cook_(cricketer)"},
    {"name": "Andrew Flintoff",          "wiki_title": "Andrew_Flintoff"},
    {"name": "Michael Vaughan",          "wiki_title": "Michael_Vaughan"},
    {"name": "Nasser Hussain",           "wiki_title": "Nasser_Hussain"},
    {"name": "Graeme Thorpe",            "wiki_title": "Graeme_Thorpe"},
    {"name": "Graham Gooch",             "wiki_title": "Graham_Gooch"},
    {"name": "Geoffrey Boycott",         "wiki_title": "Geoffrey_Boycott"},
    {"name": "David Gower",              "wiki_title": "David_Gower"},
    {"name": "Ian Botham",               "wiki_title": "Ian_Botham"},
    {"name": "Mike Gatting",             "wiki_title": "Mike_Gatting"},
    {"name": "Robin Smith",              "wiki_title": "Robin_Smith_(cricketer)"},
    {"name": "Darren Gough",             "wiki_title": "Darren_Gough"},
    {"name": "Phil Tufnell",             "wiki_title": "Phil_Tufnell"},
    {"name": "Angus Fraser",             "wiki_title": "Angus_Fraser"},
    {"name": "Derek Underwood",          "wiki_title": "Derek_Underwood"},
    {"name": "Bob Willis",               "wiki_title": "Bob_Willis"},
    {"name": "Fred Trueman",             "wiki_title": "Fred_Trueman"},
    {"name": "Jim Laker",                "wiki_title": "Jim_Laker"},
    {"name": "Tony Lock",                "wiki_title": "Tony_Lock"},
    {"name": "Colin Cowdrey",            "wiki_title": "Colin_Cowdrey"},
    {"name": "Peter May",                "wiki_title": "Peter_May_(cricketer)"},
    {"name": "Denis Compton",            "wiki_title": "Denis_Compton"},
    {"name": "Len Hutton",               "wiki_title": "Len_Hutton"},
    {"name": "Ted Dexter",               "wiki_title": "Ted_Dexter"},
    {"name": "Tom Graveney",             "wiki_title": "Tom_Graveney"},
    {"name": "Ken Barrington",           "wiki_title": "Ken_Barrington"},
    {"name": "Jack Hobbs",               "wiki_title": "Jack_Hobbs"},
    {"name": "WG Grace",                 "wiki_title": "W._G._Grace"},
    {"name": "Alec Bedser",              "wiki_title": "Alec_Bedser"},
    {"name": "Phil DeFreitas",           "wiki_title": "Phil_DeFreitas"},
    {"name": "Dominic Bess",             "wiki_title": "Dominic_Bess"},
    {"name": "Liam Livingstone",         "wiki_title": "Liam_Livingstone"},
    {"name": "Sam Curran",               "wiki_title": "Sam_Curran"},
    {"name": "Chris Woakes",             "wiki_title": "Chris_Woakes"},
    {"name": "David Willey",             "wiki_title": "David_Willey_(cricketer)"},
    {"name": "Dawid Malan",              "wiki_title": "Dawid_Malan"},
    {"name": "Phil Salt",                "wiki_title": "Phil_Salt"},
    {"name": "Will Jacks",               "wiki_title": "Will_Jacks"},
    {"name": "Jamie Smith",              "wiki_title": "Jamie_Smith_(cricketer)"},
    # ── Pakistan ──────────────────────────────────────────────────────────────
    {"name": "Babar Azam",               "wiki_title": "Babar_Azam"},
    {"name": "Shaheen Afridi",           "wiki_title": "Shaheen_Shah_Afridi"},
    {"name": "Mohammad Rizwan",          "wiki_title": "Mohammad_Rizwan_(cricketer)"},
    {"name": "Shadab Khan",              "wiki_title": "Shadab_Khan_(cricketer)"},
    {"name": "Naseem Shah",              "wiki_title": "Naseem_Shah"},
    {"name": "Hasan Ali",                "wiki_title": "Hasan_Ali_(cricketer)"},
    {"name": "Iftikhar Ahmed",           "wiki_title": "Iftikhar_Ahmed_(cricketer)"},
    {"name": "Fakhar Zaman",             "wiki_title": "Fakhar_Zaman"},
    {"name": "Imam-ul-Haq",              "wiki_title": "Imam-ul-Haq"},
    {"name": "Sarfaraz Ahmed",           "wiki_title": "Sarfaraz_Ahmed"},
    {"name": "Mohammad Hafeez",          "wiki_title": "Mohammad_Hafeez"},
    {"name": "Shoaib Malik",             "wiki_title": "Shoaib_Malik"},
    {"name": "Wasim Akram",              "wiki_title": "Wasim_Akram"},
    {"name": "Waqar Younis",             "wiki_title": "Waqar_Younis"},
    {"name": "Shoaib Akhtar",            "wiki_title": "Shoaib_Akhtar"},
    {"name": "Inzamam-ul-Haq",          "wiki_title": "Inzamam-ul-Haq"},
    {"name": "Younis Khan",              "wiki_title": "Younis_Khan"},
    {"name": "Mohammad Yousuf",          "wiki_title": "Mohammad_Yousuf"},
    {"name": "Saeed Anwar",              "wiki_title": "Saeed_Anwar"},
    {"name": "Imran Khan",               "wiki_title": "Imran_Khan"},
    {"name": "Javed Miandad",            "wiki_title": "Javed_Miandad"},
    {"name": "Mushtaq Ahmed",            "wiki_title": "Mushtaq_Ahmed"},
    {"name": "Saqlain Mushtaq",          "wiki_title": "Saqlain_Mushtaq"},
    {"name": "Umar Akmal",               "wiki_title": "Umar_Akmal"},
    {"name": "Kamran Akmal",             "wiki_title": "Kamran_Akmal"},
    {"name": "Umar Gul",                 "wiki_title": "Umar_Gul"},
    {"name": "Saeed Ajmal",              "wiki_title": "Saeed_Ajmal"},
    {"name": "Wahab Riaz",               "wiki_title": "Wahab_Riaz"},
    {"name": "Azhar Ali",                "wiki_title": "Azhar_Ali"},
    {"name": "Ahmed Shehzad",            "wiki_title": "Ahmed_Shehzad"},
    {"name": "Hanif Mohammad",           "wiki_title": "Hanif_Mohammad"},
    {"name": "Mushtaq Mohammad",         "wiki_title": "Mushtaq_Mohammad"},
    {"name": "Majid Khan",               "wiki_title": "Majid_Khan_(cricketer)"},
    {"name": "Zaheer Abbas",             "wiki_title": "Zaheer_Abbas"},
    {"name": "Asif Iqbal",               "wiki_title": "Asif_Iqbal_(cricketer)"},
    {"name": "Taufeeq Umar",             "wiki_title": "Taufeeq_Umar"},
    {"name": "Asad Shafiq",              "wiki_title": "Asad_Shafiq"},
    {"name": "Fawad Alam",               "wiki_title": "Fawad_Alam"},
    {"name": "Abid Ali",                 "wiki_title": "Abid_Ali_(cricketer,_born_1987)"},
    {"name": "Mohammad Abbas",           "wiki_title": "Mohammad_Abbas_(cricketer)"},
    {"name": "Yasir Shah",               "wiki_title": "Yasir_Shah"},
    {"name": "Shan Masood",              "wiki_title": "Shan_Masood"},
    {"name": "Abdullah Shafique",        "wiki_title": "Abdullah_Shafique"},
    {"name": "Agha Salman",              "wiki_title": "Agha_Salman"},
    {"name": "Haider Ali",               "wiki_title": "Haider_Ali_(cricketer)"},
    {"name": "Khushdil Shah",            "wiki_title": "Khushdil_Shah"},
    {"name": "Zaman Khan",               "wiki_title": "Zaman_Khan_(cricketer)"},
    {"name": "Tayyab Tahir",             "wiki_title": "Tayyab_Tahir"},
    {"name": "Rameez Raja",              "wiki_title": "Rameez_Raja"},
    {"name": "Saleem Malik",             "wiki_title": "Salim_Malik"},
    {"name": "Zahoor Ahmed",             "wiki_title": "Zulfiqar_Ahmed_(cricketer)"},
    # ── South Africa ──────────────────────────────────────────────────────────
    {"name": "AB de Villiers",           "wiki_title": "AB_de_Villiers"},
    {"name": "Graeme Smith",             "wiki_title": "Graeme_Smith_(cricketer)"},
    {"name": "Hashim Amla",              "wiki_title": "Hashim_Amla"},
    {"name": "Jacques Kallis",           "wiki_title": "Jacques_Kallis"},
    {"name": "Dale Steyn",               "wiki_title": "Dale_Steyn"},
    {"name": "Allan Donald",             "wiki_title": "Allan_Donald"},
    {"name": "Faf du Plessis",           "wiki_title": "Faf_du_Plessis"},
    {"name": "Kagiso Rabada",            "wiki_title": "Kagiso_Rabada"},
    {"name": "Quinton de Kock",          "wiki_title": "Quinton_de_Kock"},
    {"name": "Morne Morkel",             "wiki_title": "Morne_Morkel"},
    {"name": "Jonty Rhodes",             "wiki_title": "Jonty_Rhodes"},
    {"name": "Gary Kirsten",             "wiki_title": "Gary_Kirsten"},
    {"name": "Herschelle Gibbs",         "wiki_title": "Herschelle_Gibbs"},
    {"name": "Mark Boucher",             "wiki_title": "Mark_Boucher"},
    {"name": "Shaun Pollock",            "wiki_title": "Shaun_Pollock"},
    {"name": "Lance Klusener",           "wiki_title": "Lance_Klusener"},
    {"name": "Paul Adams",               "wiki_title": "Paul_Adams_(cricketer)"},
    {"name": "Mike Procter",             "wiki_title": "Mike_Procter"},
    {"name": "Barry Richards",           "wiki_title": "Barry_Richards"},
    {"name": "Graeme Pollock",           "wiki_title": "Graeme_Pollock"},
    {"name": "Kepler Wessels",           "wiki_title": "Kepler_Wessels"},
    {"name": "Temba Bavuma",             "wiki_title": "Temba_Bavuma"},
    {"name": "Aiden Markram",            "wiki_title": "Aiden_Markram"},
    {"name": "Keshav Maharaj",           "wiki_title": "Keshav_Maharaj"},
    {"name": "Lungi Ngidi",              "wiki_title": "Lungi_Ngidi"},
    {"name": "Anrich Nortje",            "wiki_title": "Anrich_Nortje"},
    {"name": "David Miller",             "wiki_title": "David_Miller_(cricketer)"},
    {"name": "Heinrich Klaasen",         "wiki_title": "Heinrich_Klaasen"},
    {"name": "Marco Jansen",             "wiki_title": "Marco_Jansen"},
    {"name": "Rilee Rossouw",            "wiki_title": "Rilee_Rossouw"},
    {"name": "Reeza Hendricks",          "wiki_title": "Reeza_Hendricks"},
    {"name": "Rassie van der Dussen",    "wiki_title": "Rassie_van_der_Dussen"},
    {"name": "Tristan Stubbs",           "wiki_title": "Tristan_Stubbs"},
    {"name": "Ryan Rickelton",           "wiki_title": "Ryan_Rickelton"},
    {"name": "Wiaan Mulder",             "wiki_title": "Wiaan_Mulder"},
    {"name": "Gerald Coetzee",           "wiki_title": "Gerald_Coetzee_(cricketer)"},
    {"name": "Tabraiz Shamsi",           "wiki_title": "Tabraiz_Shamsi"},
    {"name": "Wayne Parnell",            "wiki_title": "Wayne_Parnell"},
    {"name": "Lizaad Williams",          "wiki_title": "Lizaad_Williams"},
    {"name": "Nandre Burger",            "wiki_title": "Nandre_Burger"},
    {"name": "Ottneil Baartman",         "wiki_title": "Ottneil_Baartman"},
    {"name": "Khaya Zondo",              "wiki_title": "Khaya_Zondo"},
    {"name": "Dave Richardson",          "wiki_title": "Dave_Richardson_(cricketer)"},
    {"name": "Nicky Boje",               "wiki_title": "Nicky_Boje"},
    # ── West Indies ───────────────────────────────────────────────────────────
    {"name": "Brian Lara",               "wiki_title": "Brian_Lara"},
    {"name": "Viv Richards",             "wiki_title": "Viv_Richards"},
    {"name": "Clive Lloyd",              "wiki_title": "Clive_Lloyd"},
    {"name": "Joel Garner",              "wiki_title": "Joel_Garner"},
    {"name": "Michael Holding",          "wiki_title": "Michael_Holding"},
    {"name": "Curtly Ambrose",           "wiki_title": "Curtly_Ambrose"},
    {"name": "Courtney Walsh",           "wiki_title": "Courtney_Walsh"},
    {"name": "Chris Gayle",              "wiki_title": "Chris_Gayle_(cricketer)"},
    {"name": "Shivnarine Chanderpaul",   "wiki_title": "Shivnarine_Chanderpaul"},
    {"name": "Gordon Greenidge",         "wiki_title": "Gordon_Greenidge"},
    {"name": "Desmond Haynes",           "wiki_title": "Desmond_Haynes"},
    {"name": "Richie Richardson",        "wiki_title": "Richie_Richardson_(cricketer)"},
    {"name": "Carl Hooper",              "wiki_title": "Carl_Hooper"},
    {"name": "Garfield Sobers",          "wiki_title": "Garfield_Sobers"},
    {"name": "Frank Worrell",            "wiki_title": "Frank_Worrell"},
    {"name": "Everton Weekes",           "wiki_title": "Everton_Weekes"},
    {"name": "Clyde Walcott",            "wiki_title": "Clyde_Walcott"},
    {"name": "George Headley",           "wiki_title": "George_Headley"},
    {"name": "Lance Gibbs",              "wiki_title": "Lance_Gibbs"},
    {"name": "Andy Roberts",             "wiki_title": "Andy_Roberts_(cricketer)"},
    {"name": "Malcolm Marshall",         "wiki_title": "Malcolm_Marshall"},
    {"name": "Fidel Edwards",            "wiki_title": "Fidel_Edwards"},
    {"name": "Jerome Taylor",            "wiki_title": "Jerome_Taylor"},
    {"name": "Darren Bravo",             "wiki_title": "Darren_Bravo"},
    {"name": "Marlon Samuels",           "wiki_title": "Marlon_Samuels"},
    {"name": "Dwayne Bravo",             "wiki_title": "Dwayne_Bravo"},
    {"name": "Kieron Pollard",           "wiki_title": "Kieron_Pollard"},
    {"name": "Andre Russell",            "wiki_title": "Andre_Russell"},
    {"name": "Jason Holder",             "wiki_title": "Jason_Holder"},
    {"name": "Shimron Hetmyer",          "wiki_title": "Shimron_Hetmyer"},
    {"name": "Nicholas Pooran",          "wiki_title": "Nicholas_Pooran"},
    {"name": "Shai Hope",                "wiki_title": "Shai_Hope"},
    {"name": "Roston Chase",             "wiki_title": "Roston_Chase"},
    {"name": "Kemar Roach",              "wiki_title": "Kemar_Roach"},
    {"name": "Shannon Gabriel",          "wiki_title": "Shannon_Gabriel"},
    {"name": "Alzarri Joseph",           "wiki_title": "Alzarri_Joseph"},
    {"name": "Daren Sammy",              "wiki_title": "Darren_Sammy"},
    {"name": "Sunil Narine",             "wiki_title": "Sunil_Narine"},
    {"name": "Samuel Badree",            "wiki_title": "Samuel_Badree"},
    {"name": "Dinesh Ramdin",            "wiki_title": "Denesh_Ramdin"},
    {"name": "Evin Lewis",               "wiki_title": "Evin_Lewis"},
    {"name": "Kyle Mayers",              "wiki_title": "Kyle_Mayers"},
    {"name": "Rovman Powell",            "wiki_title": "Rovman_Powell"},
    {"name": "Brandon King",             "wiki_title": "Brandon_King_(cricketer)"},
    {"name": "Kavem Hodge",              "wiki_title": "Kavem_Hodge"},
    {"name": "Akeal Hosein",             "wiki_title": "Akeal_Hosein"},
    {"name": "Gudakesh Motie",           "wiki_title": "Gudakesh_Motie"},
    {"name": "Alick Athanaze",           "wiki_title": "Alick_Athanaze"},
    {"name": "Patrick Patterson",        "wiki_title": "Patrick_Patterson"},
    {"name": "Eldine Baptiste",          "wiki_title": "Eldine_Baptiste"},
    {"name": "Roger Harper",             "wiki_title": "Roger_Harper"},
    {"name": "Jeff Dujon",               "wiki_title": "Jeff_Dujon"},
    {"name": "Collis King",              "wiki_title": "Collis_King"},
    {"name": "Winston Davis",            "wiki_title": "Winston_Davis_(cricketer)"},
    {"name": "Milton Small",             "wiki_title": "Milton_Small_(cricketer)"},
    # ── New Zealand ───────────────────────────────────────────────────────────
    {"name": "Kane Williamson",          "wiki_title": "Kane_Williamson"},
    {"name": "Ross Taylor",              "wiki_title": "Ross_Taylor"},
    {"name": "Brendon McCullum",         "wiki_title": "Brendon_McCullum"},
    {"name": "Martin Crowe",             "wiki_title": "Martin_Crowe"},
    {"name": "Richard Hadlee",           "wiki_title": "Richard_Hadlee"},
    {"name": "Daniel Vettori",           "wiki_title": "Daniel_Vettori"},
    {"name": "Tim Southee",              "wiki_title": "Tim_Southee"},
    {"name": "Trent Boult",              "wiki_title": "Trent_Boult"},
    {"name": "Devon Conway",             "wiki_title": "Devon_Conway"},
    {"name": "John Wright",              "wiki_title": "John_Wright_(cricketer)"},
    {"name": "Glenn Turner",             "wiki_title": "Glenn_Turner_(cricketer)"},
    {"name": "Nathan Astle",             "wiki_title": "Nathan_Astle"},
    {"name": "Stephen Fleming",          "wiki_title": "Stephen_Fleming"},
    {"name": "Chris Cairns",             "wiki_title": "Chris_Cairns"},
    {"name": "Shane Bond",               "wiki_title": "Shane_Bond"},
    {"name": "Martin Guptill",           "wiki_title": "Martin_Guptill"},
    {"name": "Tom Latham",               "wiki_title": "Tom_Latham_(cricketer)"},
    {"name": "Henry Nicholls",           "wiki_title": "Henry_Nicholls_(cricketer)"},
    {"name": "Mitchell Santner",         "wiki_title": "Mitchell_Santner"},
    {"name": "Ish Sodhi",                "wiki_title": "Ish_Sodhi"},
    {"name": "Matt Henry",               "wiki_title": "Matt_Henry_(cricketer)"},
    {"name": "Neil Wagner",              "wiki_title": "Neil_Wagner"},
    {"name": "Daryl Mitchell",           "wiki_title": "Daryl_Mitchell_(cricketer)"},
    {"name": "Will Young",               "wiki_title": "Will_Young_(cricketer)"},
    {"name": "Tom Blundell",             "wiki_title": "Tom_Blundell"},
    {"name": "Tim Seifert",              "wiki_title": "Tim_Seifert"},
    {"name": "Finn Allen",               "wiki_title": "Finn_Allen_(cricketer)"},
    {"name": "Michael Bracewell",        "wiki_title": "Michael_Bracewell_(cricketer)"},
    {"name": "Glenn Phillips",           "wiki_title": "Glenn_Phillips_(cricketer)"},
    {"name": "Rachin Ravindra",          "wiki_title": "Rachin_Ravindra"},
    {"name": "Mark Chapman",             "wiki_title": "Mark_Chapman_(cricketer)"},
    {"name": "Jacob Duffy",              "wiki_title": "Jacob_Duffy_(cricketer)"},
    {"name": "Scott Styris",             "wiki_title": "Scott_Styris"},
    {"name": "Kyle Mills",               "wiki_title": "Kyle_Mills_(cricketer)"},
    {"name": "Grant Elliott",            "wiki_title": "Grant_Elliott"},
    {"name": "Corey Anderson",           "wiki_title": "Corey_Anderson_(cricketer)"},
    {"name": "Geoff Allott",             "wiki_title": "Geoff_Allott"},
    {"name": "Chris Harris",             "wiki_title": "Chris_Harris_(cricketer)"},
    {"name": "Iain O'Brien",             "wiki_title": "Iain_O%27Brien_(cricketer)"},
    # ── Sri Lanka ─────────────────────────────────────────────────────────────
    {"name": "Kumar Sangakkara",         "wiki_title": "Kumar_Sangakkara"},
    {"name": "Mahela Jayawardene",       "wiki_title": "Mahela_Jayawardene"},
    {"name": "Arjuna Ranatunga",         "wiki_title": "Arjuna_Ranatunga"},
    {"name": "Aravinda de Silva",        "wiki_title": "Aravinda_de_Silva"},
    {"name": "Muttiah Muralitharan",     "wiki_title": "Muttiah_Muralitharan"},
    {"name": "Sanath Jayasuriya",        "wiki_title": "Sanath_Jayasuriya"},
    {"name": "Lasith Malinga",           "wiki_title": "Lasith_Malinga"},
    {"name": "Chaminda Vaas",            "wiki_title": "Chaminda_Vaas"},
    {"name": "Angelo Mathews",           "wiki_title": "Angelo_Mathews"},
    {"name": "Roshan Mahanama",          "wiki_title": "Roshan_Mahanama"},
    {"name": "Asanka Gurusinha",         "wiki_title": "Asanka_Gurusinha"},
    {"name": "Romesh Kaluwitharana",     "wiki_title": "Romesh_Kaluwitharana"},
    {"name": "Hashan Tillakaratne",      "wiki_title": "Hashan_Tillakaratne"},
    {"name": "Marvan Atapattu",          "wiki_title": "Marvan_Atapattu"},
    {"name": "Thilan Samaraweera",       "wiki_title": "Thilan_Samaraweera"},
    {"name": "Tillakaratne Dilshan",     "wiki_title": "Tillakaratne_Dilshan"},
    {"name": "Upul Tharanga",            "wiki_title": "Upul_Tharanga"},
    {"name": "Dinesh Chandimal",         "wiki_title": "Dinesh_Chandimal"},
    {"name": "Lahiru Thirimanne",        "wiki_title": "Lahiru_Thirimanne"},
    {"name": "Kusal Perera",             "wiki_title": "Kusal_Perera"},
    {"name": "Kusal Mendis",             "wiki_title": "Kusal_Mendis"},
    {"name": "Dimuth Karunaratne",       "wiki_title": "Dimuth_Karunaratne"},
    {"name": "Dhananjaya de Silva",      "wiki_title": "Dhananjaya_de_Silva"},
    {"name": "Wanindu Hasaranga",        "wiki_title": "Wanindu_Hasaranga"},
    {"name": "Maheesh Theekshana",       "wiki_title": "Maheesh_Theekshana"},
    {"name": "Pathum Nissanka",          "wiki_title": "Pathum_Nissanka"},
    {"name": "Charith Asalanka",         "wiki_title": "Charith_Asalanka"},
    {"name": "Pramod Madushan",          "wiki_title": "Pramod_Madushan"},
    {"name": "Nuwan Kulasekara",         "wiki_title": "Nuwan_Kulasekara"},
    {"name": "Rangana Herath",           "wiki_title": "Rangana_Herath"},
    {"name": "Lakshan Sandakan",         "wiki_title": "Lakshan_Sandakan"},
    {"name": "Akila Dananjaya",          "wiki_title": "Akila_Dananjaya"},
    {"name": "Lahiru Kumara",            "wiki_title": "Lahiru_Kumara"},
    {"name": "Dushmantha Chameera",      "wiki_title": "Dushmantha_Chameera"},
    {"name": "Asitha Fernando",          "wiki_title": "Asitha_Fernando"},
    {"name": "Jeffrey Vandersay",        "wiki_title": "Jeffrey_Vandersay"},
    {"name": "Sadeera Samarawickrama",   "wiki_title": "Sadeera_Samarawickrama"},
    {"name": "Chamika Karunaratne",      "wiki_title": "Chamika_Karunaratne"},
    {"name": "Dunith Wellalage",         "wiki_title": "Dunith_Wellalage"},
    {"name": "Matheesha Pathirana",      "wiki_title": "Matheesha_Pathirana"},
    {"name": "Janith Liyanage",          "wiki_title": "Janith_Liyanage"},
    {"name": "Nuwanidu Fernando",        "wiki_title": "Nuwanidu_Fernando"},
    # ── Bangladesh ────────────────────────────────────────────────────────────
    {"name": "Shakib Al Hasan",          "wiki_title": "Shakib_Al_Hasan"},
    {"name": "Tamim Iqbal",              "wiki_title": "Tamim_Iqbal"},
    {"name": "Mushfiqur Rahim",          "wiki_title": "Mushfiqur_Rahim"},
    {"name": "Mashrafe Mortaza",         "wiki_title": "Mashrafe_Mortaza"},
    {"name": "Mahmudullah",              "wiki_title": "Mahmudullah"},
    {"name": "Mominul Haque",            "wiki_title": "Mominul_Haque"},
    {"name": "Liton Das",                "wiki_title": "Liton_Das"},
    {"name": "Mehidy Hasan Miraz",       "wiki_title": "Mehidy_Hasan_Miraz"},
    {"name": "Taijul Islam",             "wiki_title": "Taijul_Islam"},
    {"name": "Rubel Hossain",            "wiki_title": "Rubel_Hossain"},
    {"name": "Mustafizur Rahman",        "wiki_title": "Mustafizur_Rahman"},
    {"name": "Taskin Ahmed",             "wiki_title": "Taskin_Ahmed"},
    {"name": "Soumya Sarkar",            "wiki_title": "Soumya_Sarkar"},
    {"name": "Nazmul Hossain Shanto",    "wiki_title": "Nazmul_Hossain_Shanto"},
    {"name": "Nasum Ahmed",              "wiki_title": "Nasum_Ahmed"},
    {"name": "Shoriful Islam",           "wiki_title": "Shoriful_Islam"},
    {"name": "Tanzid Hasan",             "wiki_title": "Tanzid_Hasan"},
    {"name": "Mahedi Hasan",             "wiki_title": "Mahedi_Hasan_(cricketer)"},
    {"name": "Afif Hossain",             "wiki_title": "Afif_Hossain"},
    {"name": "Yasir Ali",                "wiki_title": "Yasir_Ali_(cricketer)"},
    {"name": "Ebadot Hossain",           "wiki_title": "Ebadot_Hossain"},
    {"name": "Hasan Mahmud",             "wiki_title": "Hasan_Mahmud_(cricketer)"},
    {"name": "Habibul Bashar",           "wiki_title": "Habibul_Bashar"},
    {"name": "Mohammad Rafique",         "wiki_title": "Mohammad_Rafique"},
    {"name": "Khaled Mahmud",            "wiki_title": "Khaled_Mahmud"},
    {"name": "Alok Kapali",              "wiki_title": "Alok_Kapali"},
    # ── Afghanistan ───────────────────────────────────────────────────────────
    {"name": "Rashid Khan",              "wiki_title": "Rashid_Khan_(cricketer)"},
    {"name": "Mohammad Nabi",            "wiki_title": "Mohammad_Nabi_(cricketer)"},
    {"name": "Mujeeb Ur Rahman",         "wiki_title": "Mujeeb_Ur_Rahman"},
    {"name": "Asghar Afghan",            "wiki_title": "Asghar_Afghan"},
    {"name": "Hashmatullah Shahidi",     "wiki_title": "Hashmatullah_Shahidi"},
    {"name": "Rahmanullah Gurbaz",       "wiki_title": "Rahmanullah_Gurbaz"},
    {"name": "Ibrahim Zadran",           "wiki_title": "Ibrahim_Zadran"},
    {"name": "Najibullah Zadran",        "wiki_title": "Najibullah_Zadran"},
    {"name": "Azmatullah Omarzai",       "wiki_title": "Azmatullah_Omarzai"},
    {"name": "Gulbadin Naib",            "wiki_title": "Gulbadin_Naib"},
    {"name": "Naveen-ul-Haq",            "wiki_title": "Naveen-ul-Haq"},
    {"name": "Noor Ahmad",               "wiki_title": "Noor_Ahmad_(cricketer)"},
    {"name": "Fazalhaq Farooqi",         "wiki_title": "Fazalhaq_Farooqi"},
    {"name": "Karim Janat",              "wiki_title": "Karim_Janat"},
    {"name": "Rahmat Shah",              "wiki_title": "Rahmat_Shah_(cricketer)"},
    {"name": "Ikram Alikhil",            "wiki_title": "Ikram_Alikhil"},
    {"name": "Riaz Hassan",              "wiki_title": "Riaz_Hassan_(cricketer)"},
    {"name": "Darwish Rasooli",          "wiki_title": "Darwish_Rasooli"},
    {"name": "Farhan Zakhil",            "wiki_title": "Farhan_Zakhil"},
    {"name": "Sediqullah Atal",          "wiki_title": "Sediqullah_Atal"},
    # ── Zimbabwe ──────────────────────────────────────────────────────────────
    {"name": "Andy Flower",              "wiki_title": "Andy_Flower"},
    {"name": "Heath Streak",             "wiki_title": "Heath_Streak"},
    {"name": "Grant Flower",             "wiki_title": "Grant_Flower"},
    {"name": "Murray Goodwin",           "wiki_title": "Murray_Goodwin"},
    {"name": "Alistair Campbell",        "wiki_title": "Alistair_Campbell_(cricketer)"},
    {"name": "Henry Olonga",             "wiki_title": "Henry_Olonga"},
    {"name": "Eddo Brandes",             "wiki_title": "Eddo_Brandes"},
    {"name": "Sean Ervine",              "wiki_title": "Sean_Ervine"},
    {"name": "Brendan Taylor",           "wiki_title": "Brendan_Taylor_(cricketer)"},
    {"name": "Craig Ervine",             "wiki_title": "Craig_Ervine"},
    {"name": "Sikandar Raza",            "wiki_title": "Sikandar_Raza"},
    {"name": "Sean Williams",            "wiki_title": "Sean_Williams_(cricketer)"},
    {"name": "Blessing Muzarabani",      "wiki_title": "Blessing_Muzarabani"},
    {"name": "Tendai Chatara",           "wiki_title": "Tendai_Chatara"},
    {"name": "Ryan Burl",                "wiki_title": "Ryan_Burl"},
    {"name": "Innocent Kaia",            "wiki_title": "Innocent_Kaia"},
    {"name": "Tadiwanashe Marumani",     "wiki_title": "Tadiwanashe_Marumani"},
    {"name": "Clive Madande",            "wiki_title": "Clive_Madande"},
    {"name": "Wellington Masakadza",     "wiki_title": "Wellington_Masakadza"},
    {"name": "Donald Tiripano",          "wiki_title": "Donald_Tiripano"},
    {"name": "Victor Nyauchi",           "wiki_title": "Victor_Nyauchi"},
    {"name": "Brian Chari",              "wiki_title": "Brian_Chari"},
    {"name": "Dion Myers",               "wiki_title": "Dion_Myers"},
    {"name": "Neil Johnson",             "wiki_title": "Neil_Johnson_(cricketer)"},
    # ── Ireland ───────────────────────────────────────────────────────────────
    {"name": "Paul Stirling",            "wiki_title": "Paul_Stirling_(cricketer)"},
    {"name": "William Porterfield",      "wiki_title": "William_Porterfield"},
    {"name": "Kevin O'Brien",            "wiki_title": "Kevin_O%27Brien_(cricketer)"},
    {"name": "Niall O'Brien",            "wiki_title": "Niall_O%27Brien_(cricketer)"},
    {"name": "Trent Johnston",           "wiki_title": "Trent_Johnston"},
    {"name": "Andrew McBrine",           "wiki_title": "Andrew_McBrine"},
    {"name": "Lorcan Tucker",            "wiki_title": "Lorcan_Tucker"},
    {"name": "Harry Tector",             "wiki_title": "Harry_Tector"},
    {"name": "Mark Adair",               "wiki_title": "Mark_Adair_(cricketer)"},
    {"name": "Simi Singh",               "wiki_title": "Simi_Singh_(cricketer)"},
    {"name": "George Dockrell",          "wiki_title": "George_Dockrell"},
    {"name": "Curtis Campher",           "wiki_title": "Curtis_Campher"},
    {"name": "Murray Commins",           "wiki_title": "Murray_Commins"},
    # ── Scotland ──────────────────────────────────────────────────────────────
    {"name": "Kyle Coetzer",             "wiki_title": "Kyle_Coetzer"},
    {"name": "Calum MacLeod",            "wiki_title": "Calum_MacLeod"},
    {"name": "Richie Berrington",        "wiki_title": "Richie_Berrington"},
    {"name": "Matthew Cross",            "wiki_title": "Matthew_Cross_(cricketer)"},
    {"name": "George Munsey",            "wiki_title": "George_Munsey"},
    {"name": "Michael Jones",            "wiki_title": "Michael_Jones_(cricketer)"},
    {"name": "Safyaan Sharif",           "wiki_title": "Safyaan_Sharif"},
    {"name": "Mark Watt",                "wiki_title": "Mark_Watt_(cricketer)"},
    {"name": "Hamza Tahir",              "wiki_title": "Hamza_Tahir"},
    # ── Netherlands ───────────────────────────────────────────────────────────
    {"name": "Ryan ten Doeschate",       "wiki_title": "Ryan_ten_Doeschate"},
    {"name": "Bas de Leede",             "wiki_title": "Bas_de_Leede"},
    {"name": "Max O'Dowd",               "wiki_title": "Max_O%27Dowd"},
    {"name": "Scott Edwards",            "wiki_title": "Scott_Edwards_(cricketer)"},
    {"name": "Vikramjit Singh",          "wiki_title": "Vikramjit_Singh_(cricketer)"},
    {"name": "Teja Nidamanuru",          "wiki_title": "Teja_Nidamanuru"},
    {"name": "Tim Pringle",              "wiki_title": "Tim_Pringle_(cricketer)"},
    {"name": "Stephan Myburgh",          "wiki_title": "Stephan_Myburgh"},
    {"name": "Fred Klaassen",            "wiki_title": "Fred_Klaassen"},
    {"name": "Logan van Beek",           "wiki_title": "Logan_van_Beek"},
    # ── Namibia ───────────────────────────────────────────────────────────────
    {"name": "Gerhard Erasmus",          "wiki_title": "Gerhard_Erasmus"},
    {"name": "Jan Frylinck",             "wiki_title": "Jan_Frylinck"},
    {"name": "Michael van Lingen",       "wiki_title": "Michael_van_Lingen"},
    {"name": "Divan la Cock",            "wiki_title": "Divan_la_Cock"},
    {"name": "Ben Shikongo",             "wiki_title": "Ben_Shikongo"},
    {"name": "Pikky Ya France",          "wiki_title": "Pikky_Ya_France"},
    {"name": "Craig Williams",           "wiki_title": "Craig_Williams_(Namibian_cricketer)"},
    {"name": "Zane Green",               "wiki_title": "Zane_Green_(cricketer)"},
    # ── Oman / UAE ────────────────────────────────────────────────────────────
    {"name": "Zeeshan Maqsood",          "wiki_title": "Zeeshan_Maqsood"},
    {"name": "Aqib Ilyas",               "wiki_title": "Aqib_Ilyas"},
    {"name": "Muhammad Waseem",          "wiki_title": "Muhammad_Waseem_(cricketer)"},
    {"name": "Basil Hameed",             "wiki_title": "Basil_Hameed"},
    {"name": "Rohan Mustafa",            "wiki_title": "Rohan_Mustafa"},
    {"name": "Vriitya Aravind",          "wiki_title": "Vriitya_Aravind"},
    {"name": "Khurram Khan",             "wiki_title": "Khurram_Khan_(cricketer)"},
    # ── Nepal ─────────────────────────────────────────────────────────────────
    {"name": "Sandeep Lamichhane",       "wiki_title": "Sandeep_Lamichhane"},
    {"name": "Paras Khadka",             "wiki_title": "Paras_Khadka"},
    {"name": "Dipendra Singh Airee",     "wiki_title": "Dipendra_Singh_Airee"},
    {"name": "Rohit Kumar Paudel",       "wiki_title": "Rohit_Kumar_Paudel"},
    {"name": "Gulshan Jha",              "wiki_title": "Gulshan_Jha"},
    {"name": "Lalit Rajbanshi",          "wiki_title": "Lalit_Rajbanshi"},
    # ── Papua New Guinea ──────────────────────────────────────────────────────
    {"name": "Assad Vala",               "wiki_title": "Assad_Vala"},
    {"name": "Norman Vanua",             "wiki_title": "Norman_Vanua"},
    {"name": "Damian Ravu",              "wiki_title": "Damian_Ravu"},
    {"name": "Charles Amini",            "wiki_title": "Charles_Amini"},
    {"name": "Tony Ura",                 "wiki_title": "Tony_Ura"},
    {"name": "Lega Siaka",               "wiki_title": "Lega_Siaka"},
    # ── Kenya ─────────────────────────────────────────────────────────────────
    {"name": "Collins Obuya",            "wiki_title": "Collins_Obuya"},
    {"name": "Steve Tikolo",             "wiki_title": "Steve_Tikolo"},
    {"name": "Thomas Odoyo",             "wiki_title": "Thomas_Odoyo"},
    {"name": "Kennedy Otieno",           "wiki_title": "Kennedy_Otieno"},
    # ── USA ───────────────────────────────────────────────────────────────────
    {"name": "Monank Patel",             "wiki_title": "Monank_Patel"},
    {"name": "Aaron Jones",              "wiki_title": "Aaron_Jones_(cricketer)"},
    {"name": "Andries Gous",             "wiki_title": "Andries_Gous"},
    {"name": "Saurabh Netravalkar",      "wiki_title": "Saurabh_Netravalkar"},
    {"name": "Harmeet Singh",            "wiki_title": "Harmeet_Singh_(cricketer)"},
    {"name": "Corey Anderson",           "wiki_title": "Corey_Anderson_(cricketer)"},
    {"name": "Milind Kumar",             "wiki_title": "Milind_Kumar_(cricketer)"},
    {"name": "Nisarg Patel",             "wiki_title": "Nisarg_Patel"},
    {"name": "Steven Taylor",            "wiki_title": "Steven_Taylor_(cricketer)"},
    # ── Canada ────────────────────────────────────────────────────────────────
    {"name": "Navneet Dhaliwal",         "wiki_title": "Navneet_Dhaliwal"},
    {"name": "Shreyas Movva",            "wiki_title": "Shreyas_Movva"},
    {"name": "Jeremy Gordon",            "wiki_title": "Jeremy_Gordon_(cricketer)"},
    {"name": "Saad Bin Zafar",           "wiki_title": "Saad_Bin_Zafar"},
    # ── Historical Legends ────────────────────────────────────────────────────
    {"name": "Clarrie Grimmett",         "wiki_title": "Clarrie_Grimmett"},
    {"name": "Bill O'Reilly",            "wiki_title": "Bill_O%27Reilly_(cricketer)"},
    {"name": "Lindsay Hassett",          "wiki_title": "Lindsay_Hassett"},
    {"name": "Sid Barnes",               "wiki_title": "Sid_Barnes_(cricketer)"},
    {"name": "Bill Brown",               "wiki_title": "Bill_Brown_(cricketer)"},
    {"name": "Ian Craig",                "wiki_title": "Ian_Craig_(cricketer)"},
    {"name": "Ian Redpath",              "wiki_title": "Ian_Redpath"},
    {"name": "Paul Reiffel",             "wiki_title": "Paul_Reiffel"},
    {"name": "Damien Fleming",           "wiki_title": "Damien_Fleming"},
    {"name": "Michael Kasprowicz",       "wiki_title": "Michael_Kasprowicz"},
    {"name": "Carl Rackemann",           "wiki_title": "Carl_Rackemann"},
    {"name": "Geoff Lawson",             "wiki_title": "Geoff_Lawson"},
    {"name": "Tom Moody",                "wiki_title": "Tom_Moody_(cricketer)"},
    {"name": "Dean Headley",             "wiki_title": "Dean_Headley"},
    {"name": "Martin McCague",           "wiki_title": "Martin_McCague"},
    {"name": "Ashley Giles",             "wiki_title": "Ashley_Giles"},
    {"name": "Matthew Hoggard",          "wiki_title": "Matthew_Hoggard"},
    {"name": "Steve Harmison",           "wiki_title": "Steve_Harmison"},
    {"name": "Simon Jones",              "wiki_title": "Simon_Jones_(cricketer)"},
    {"name": "Graham Dilley",            "wiki_title": "Graham_Dilley"},
    {"name": "Norman Gifford",           "wiki_title": "Norman_Gifford"},
    {"name": "John Emburey",             "wiki_title": "John_Emburey"},
    {"name": "John Snow",                "wiki_title": "John_Snow_(cricketer)"},
    {"name": "Barry Wood",               "wiki_title": "Barry_Wood_(cricketer)"},
    {"name": "Dennis Amiss",             "wiki_title": "Dennis_Amiss"},
    {"name": "Peter Willey",             "wiki_title": "Peter_Willey"},
    {"name": "Vivian Richards",          "wiki_title": "Viv_Richards"},
    {"name": "Learie Constantine",       "wiki_title": "Learie_Constantine"},
    {"name": "Rohan Kanhai",             "wiki_title": "Rohan_Kanhai"},
    {"name": "Seymour Nurse",            "wiki_title": "Seymour_Nurse"},
    {"name": "Conrad Hunte",             "wiki_title": "Conrad_Hunte"},
    {"name": "Gerry Gomez",              "wiki_title": "Gerry_Gomez"},
    {"name": "Sonny Ramadhin",           "wiki_title": "Sonny_Ramadhin"},
    {"name": "Alf Valentine",            "wiki_title": "Alf_Valentine"},
    {"name": "Wally Hammond",            "wiki_title": "Wally_Hammond"},
    {"name": "Herbert Sutcliffe",        "wiki_title": "Herbert_Sutcliffe"},
    {"name": "Bill Edrich",              "wiki_title": "Bill_Edrich"},
    {"name": "Cyril Washbrook",          "wiki_title": "Cyril_Washbrook"},
    {"name": "Godfrey Evans",            "wiki_title": "Godfrey_Evans"},
    {"name": "Maurice Tate",             "wiki_title": "Maurice_Tate_(cricketer)"},
    {"name": "Harold Larwood",           "wiki_title": "Harold_Larwood"},
    {"name": "Bill Voce",                "wiki_title": "Bill_Voce"},
    {"name": "Lala Amarnath",            "wiki_title": "Lala_Amarnath"},
    {"name": "Vijay Merchant",           "wiki_title": "Vijay_Merchant"},
    {"name": "Mushtaq Ali",              "wiki_title": "Mushtaq_Ali_(cricketer)"},
    {"name": "Polly Umrigar",            "wiki_title": "Polly_Umrigar"},
    {"name": "Rusi Modi",                "wiki_title": "Rusi_Modi"},
    {"name": "Ghulam Ahmed",             "wiki_title": "Ghulam_Ahmed_(cricketer)"},
    {"name": "Kripal Singh",             "wiki_title": "Kripal_Singh"},
    {"name": "Vinoo Mankad",             "wiki_title": "Vinoo_Mankad"},
    {"name": "AG Kripal Singh",          "wiki_title": "Kripal_Singh"},
    # More Recent International Players
    {"name": "Shaun Tait",               "wiki_title": "Shaun_Tait"},
    {"name": "Mitchell Johnson",         "wiki_title": "Mitchell_Johnson_(cricketer)"},
    {"name": "Peter Nevill",             "wiki_title": "Peter_Nevill_(cricketer)"},
    {"name": "Ryan Ten Doeschate",       "wiki_title": "Ryan_ten_Doeschate"},
    {"name": "Niroshan Dickwella",       "wiki_title": "Niroshan_Dickwella"},
    {"name": "Suranga Lakmal",           "wiki_title": "Suranga_Lakmal"},
    {"name": "Lahiru Thirimanne",        "wiki_title": "Lahiru_Thirimanne"},
    {"name": "Asela Gunaratne",          "wiki_title": "Asela_Gunaratne"},
    {"name": "Dasun Shanaka",            "wiki_title": "Dasun_Shanaka"},
    {"name": "Bhanuka Rajapaksa",        "wiki_title": "Bhanuka_Rajapaksa"},
    {"name": "Minod Bhanuka",            "wiki_title": "Bhanuka_Rajapaksa"},
    {"name": "Shanaka Dasun",            "wiki_title": "Dasun_Shanaka"},
    {"name": "Kamindu Mendis",           "wiki_title": "Kamindu_Mendis"},
    {"name": "Prabath Jayasuriya",       "wiki_title": "Prabath_Jayasuriya"},
    {"name": "Nuwan Thushara",           "wiki_title": "Nuwan_Thushara"},
    {"name": "Isuru Udana",              "wiki_title": "Isuru_Udana"},
    {"name": "Milinda Siriwardana",      "wiki_title": "Milinda_Siriwardana"},
    {"name": "Sachith Pathirana",        "wiki_title": "Sachith_Pathirana"},
    {"name": "Ambati Rayudu",            "wiki_title": "Ambati_Rayudu"},
    {"name": "Punit Bisht",              "wiki_title": "Punit_Bisht"},
    {"name": "Naman Ojha",               "wiki_title": "Naman_Ojha"},
    {"name": "Stuart Binny",             "wiki_title": "Stuart_Binny"},
    {"name": "Dhawal Kulkarni",          "wiki_title": "Dhawal_Kulkarni"},
    {"name": "Jayant Yadav",             "wiki_title": "Jayant_Yadav"},
    {"name": "Karun Nair",               "wiki_title": "Karun_Nair"},
    {"name": "Lokesh Rahul",             "wiki_title": "KL_Rahul"},
    {"name": "Gurkeerat Singh Mann",     "wiki_title": "Gurkeerat_Singh_Mann"},
    {"name": "Mandeep Singh",            "wiki_title": "Mandeep_Singh_(cricketer)"},
    {"name": "Mayank Agarwal",           "wiki_title": "Mayank_Agarwal"},
    {"name": "Hanuma Vihari",            "wiki_title": "Hanuma_Vihari"},
    {"name": "Vijay Shankar",            "wiki_title": "Vijay_Shankar_(cricketer)"},
    {"name": "Srikar Bharat",            "wiki_title": "Srikar_Bharat"},
    {"name": "Sarfaraz Khan",            "wiki_title": "Sarfaraz_Khan_(cricketer)"},
    {"name": "Rinku Singh",              "wiki_title": "Rinku_Singh_(cricketer)"},
    {"name": "Jitesh Sharma",            "wiki_title": "Jitesh_Sharma"},
    {"name": "Rahul Chahar",             "wiki_title": "Rahul_Chahar"},
    {"name": "Ravi Bishnoi",             "wiki_title": "Ravi_Bishnoi"},
    {"name": "Umran Malik",              "wiki_title": "Umran_Malik"},
    {"name": "Mukesh Kumar",             "wiki_title": "Mukesh_Kumar_(cricketer)"},
    {"name": "Akash Deep",               "wiki_title": "Akash_Deep_(cricketer)"},
    {"name": "Yash Dayal",               "wiki_title": "Yash_Dayal"},
    {"name": "Kuldeep Sen",              "wiki_title": "Kuldeep_Sen"},
    {"name": "Sanvir Singh",             "wiki_title": "Sanvir_Singh"},
    {"name": "Tushar Deshpande",         "wiki_title": "Tushar_Deshpande"},
    {"name": "Riyan Parag",              "wiki_title": "Riyan_Parag"},
    {"name": "Abhishek Sharma",          "wiki_title": "Abhishek_Sharma_(cricketer)"},
    {"name": "Dhruv Jurel",              "wiki_title": "Dhruv_Jurel"},
    {"name": "KS Bharat",                "wiki_title": "Srikar_Bharat"},
    {"name": "Shamar Joseph",            "wiki_title": "Shamar_Joseph"},
    {"name": "Hayden Walsh Jr",          "wiki_title": "Hayden_Walsh_Jr"},
    {"name": "Romario Shepherd",         "wiki_title": "Romario_Shepherd"},
    {"name": "Joshua Da Silva",          "wiki_title": "Joshua_Da_Silva"},
    {"name": "Kavem Hodge",              "wiki_title": "Kavem_Hodge"},
    {"name": "Justin Greaves",           "wiki_title": "Justin_Greaves_(cricketer)"},
    {"name": "Kirk McKenzie",            "wiki_title": "Kirk_McKenzie"},
    {"name": "Anderson Phillip",         "wiki_title": "Anderson_Phillip"},
    {"name": "Jayden Seales",            "wiki_title": "Jayden_Seales"},
    {"name": "Mitch Swepson",            "wiki_title": "Mitchell_Swepson"},
    {"name": "Jhye Richardson",          "wiki_title": "Jhye_Richardson"},
    {"name": "Riley Meredith",           "wiki_title": "Riley_Meredith"},
    {"name": "Xavier Bartlett",          "wiki_title": "Xavier_Bartlett"},
    {"name": "Spencer Johnson",          "wiki_title": "Spencer_Johnson_(cricketer)"},
    {"name": "Matt Short",               "wiki_title": "Matthew_Short_(cricketer)"},
    {"name": "Jake Fraser-McGurk",       "wiki_title": "Jake_Fraser-McGurk"},
    {"name": "Cooper Connolly",          "wiki_title": "Cooper_Connolly"},
    {"name": "Josh Philippe",            "wiki_title": "Josh_Philippe"},
    {"name": "Ben McDermott",            "wiki_title": "Ben_McDermott_(cricketer)"},
    {"name": "Dan Christian",            "wiki_title": "Dan_Christian_(cricketer)"},
    {"name": "Nathan Ellis",             "wiki_title": "Nathan_Ellis_(cricketer)"},
    {"name": "Tom Rogers",               "wiki_title": "Tom_Rogers_(cricketer)"},
    {"name": "Ollie Robinson",           "wiki_title": "Ollie_Robinson_(cricketer)"},
    {"name": "Matthew Potts",            "wiki_title": "Matthew_Potts"},
    {"name": "Brydon Carse",             "wiki_title": "Brydon_Carse"},
    {"name": "Gus Atkinson",             "wiki_title": "Gus_Atkinson"},
    {"name": "Josh Hull",                "wiki_title": "Josh_Hull_(cricketer)"},
    {"name": "Shoaib Bashir",            "wiki_title": "Shoaib_Bashir"},
    {"name": "Tom Hartley",              "wiki_title": "Tom_Hartley_(cricketer)"},
    {"name": "Ben Lawrence",             "wiki_title": "Ben_Lawrence_(cricketer)"},
    {"name": "Mohammad Nawaz",           "wiki_title": "Mohammad_Nawaz_(cricketer)"},
    {"name": "Aamer Jamal",              "wiki_title": "Aamer_Jamal"},
    {"name": "Saim Ayub",                "wiki_title": "Saim_Ayub"},
    {"name": "Usman Qadir",              "wiki_title": "Usman_Qadir"},
    {"name": "Haris Rauf",               "wiki_title": "Haris_Rauf"},
    {"name": "Mohammad Wasim Jr",        "wiki_title": "Mohammad_Wasim_Jr"},
    {"name": "Irfan Khan Niazi",         "wiki_title": "Irfan_Khan_(cricketer)"},
    {"name": "Kamran Ghulam",            "wiki_title": "Kamran_Ghulam"},
    {"name": "Omair Bin Yousuf",         "wiki_title": "Omair_Bin_Yousuf"},
    {"name": "Azan Awais",               "wiki_title": "Azan_Awais"},
]
